### ISSUE TITLE
request support for sparql

### ISSUE THREAD

**Issue by amorgat** [vatlab/SoS#869] opened 2018-01-25 17:24 UTC
I'd like to use a sparql kernel (e.g https://github.com/paulovn/sparql-kernel) inside a SoS notebook and exchange data (SPARQL queries or SPARQL results) with the other kernels.
Do you think it could be manageable?

**Comment by BoPeng** [comment] 2018-01-25 17:35
I can confirm that sparql works in SoS. If we need a language module for it, we will need some reference for  types of variables used in sparql.

![image](https://user-images.githubusercontent.com/9889312/35402865-705cb10a-01c3-11e8-87af-364207382673.png)

**Comment by BoPeng** [comment] 2018-01-25 17:52
OK, my understanding from https://github.com/paulovn/sparql-kernel/issues/20 is that there is no concept of variables in this kernel so magics such as `%get` does not make sense. As @paulovn pointed out, your best bet would be outputting the results to a file and process them in another language. Something like

![image](https://user-images.githubusercontent.com/9889312/35403658-037cd72e-01c6-11e8-916c-ba757f03e3e5.png)

**Comment by paulovn** [comment] 2018-01-25 22:14
Hi. Given that the `%expand` magic essentially covers the task of inserting variables in the kernel (since input to SPARQL queries are basically strings), what may remain is fetching query results. Though the hack of saving to a file works, it might also be possible to load query results on demand in a pre-defined variable so that they are made available. 

SPARQL query result format depends on the MIME type requested to the endpoint, but for export purposes it could be a JSON (or, if format is N3, a table that could be exported as a dataframe-like structure).

I'll try to take a look at the documentation for getting variables out of the kernel and into SoS, to see how difficult would that be

**Comment by BoPeng** [comment] 2018-01-25 22:47
Parsing output file from sparql in Python or R is almost good enough because most languages can parse JSON. [A new `capture` magic ](https://github.com/vatlab/sos-notebook/issues/32) can help a bit but you would have to transfer the variables to another kernel (e.g. `R`) if you need to process the data in another kernels. So in the end you are looking at something like

```
%capture --from output.txt --to var
%outfile output.txt
sparql stuff

---- (R)
%get var

R stuff
```

**Comment by amorgat** [comment] 2018-01-27 16:33
Thanks guys!
I have been able to convert my working notebook (sparql kernel) into a sos notebook and use %outfile to exchange data with another notebook. Waiting you to transfer variables ;-)

**Comment by BoPeng** [comment] 2018-01-27 16:43
Note that there is now a new %capture json —from file —to var magic to create a dictionary from file. It will be included in the next release of sos-notebook after more testing.

**Comment by amorgat** [comment] 2018-01-27 19:44
goody!!

**Closed** 2018-01-30 02:28 UTC
