### ISSUE TITLE
Comments seem not to be ignored

### ISSUE THREAD

**Issue by N7DR** [vatlab/sos#1363] opened 2020-04-27 02:47 UTC
Executing this workflow cell:

```
%run get_180_phase
[initialise_variables: shared=['h', 'rh', 'd', 'db', 'QED_PROG']]
# set values for the scenario

h = 1e+06
rh = 1e+06
d = 2e+06
db = 1e-07

QED_PROG = "~/codelite/qed/Debug/qed"

[get_180_phase]
depends: sos_variable('h'), sos_variable('rh'), sos_variable('d'), sos_variable('db'), sos_variable('QED_PROG')
bash: expand=True

{QED_PROG} -s 0 -h {h} -rh {rh} -d {d} -db {db} -bmin 0 -bmax 180

#[capture_phase: shared='resultant_phase']
#resultant_phase = _output.split()[3][:-1]

#[components_1deg_bins]
#input: resultant_phase
#bash: expand=True
#
#export BIN_WIDTH='1'
#export OUTFILE='component-1.txt'
#
#>$OUTFILE
#
#for i in $(seq 0 $BIN_WIDTH `bc <<< "180 - $BIN_WIDTH"`)
#do
#  {QED_PROG} -s 1 -h {h} -rh {rh} -d {d} -db {db} -bmin $i -bmax `bc <<< "$i + $BIN_WIDTH"` -ph {resultant_phase} >> $OUTFILE
#done

```
(all the text between the two "----" lines is in one cell)

I get the following error:
```
INFO: Running initialise_variables:
INFO: initialise_variables output: QED_PROG
INFO: Running get_180_phase:

ERROR: [get_180_phase]: [0]: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
script_8987463565533973459 in <module>
      #  {QED_PROG} -s 1 -h {h} -rh {rh} -d {d} -db {db} -bmin $i -bmax `bc <<< "$i + $BIN_WIDTH"` -ph {resultant_phase} >> $OUTFILE
      #done
----> """)
      

NameError: name 'resultant_phase' is not defined

Workflow exited with code 1

```
I expected that the lines that start with an octothorpe would be treated as comments, but it seems that they are not :-(

So how do I correctly mark a line as a comment? (that is, all the lines in the cell after the one that begins with: {QED_PROG} )

**Comment by N7DR** [comment] 2020-04-27 02:51
file:///tmp/example.txt

**Comment by gaow** [comment] 2020-04-27 03:58
@N7DR I'll leave the comment string interpolation issue to @BoPeng. But for your pipeline, why don't you use `global` section to define parameters? 

```
[global]
h = 1e+06
rh = 1e+06
d = 2e+06
db = 1e-07
QED_PROG = "~/codelite/qed/Debug/qed"

[get_180_phase]
bash: expand=True
  {QED_PROG} -s 0 -h {h} -rh {rh} -d {d} -db {db} -bmin 0 -bmax 180
```

**Comment by BoPeng** [comment] 2020-04-27 04:12
For 

```
bash: expand=True

{QED_PROG} -s 0 -h {h} -rh {rh} -d {d} -db {db} -bmin 0 -bmax 180

#[capture_phase: shared='resultant_phase']
#resultant_phase = _output.split()[3][:-1]

```
because you did not indent `{QED_...`, SoS assumes the following `#` lines are part of the shell script and is expanded.

This is by design because `#` could be significant in some languages.

**Comment by BoPeng** [comment] 2020-04-27 04:26
@gaow Like many other features that were added for flexibility or kept for compatibility, we allow script to be included without indentation, and in this case caused confusion. Perhaps a warning message could be added here?

**Comment by gaow** [comment] 2020-04-27 04:40
Thank you @BoPeng I didn't realize this is artifact due to unindented script. I agree a warning message would be a good way to discourage its use while retaining backward compatibility.

**Comment by N7DR** [comment] 2020-04-27 14:27
Bo wrote on 4/26/20 10:12 PM:
> For 
> 
> ```
> bash: expand=True
> 
> {QED_PROG} -s 0 -h {h} -rh {rh} -d {d} -db {db} -bmin 0 -bmax 180
> 
> #[capture_phase: shared='resultant_phase']
> #resultant_phase = _output.split()[3][:-1]
> 
> ```
> because you did not indent `{QED_...`, SoS assumes the following `#` lines are part of the shell script and is expanded.
> 
> This is by design because `#` could be significant in some languages.
> 

I find this very surprising and confusing, and it surely must be documented in
detail somewhere... after all, it is common practice to stick a "#" at the
start of a line in bash to mark the rest of the line as a comment. So if it
were true that "the following `#` lines are part of the shell script", then
they would be ignored. Which is what I expected; but is not what is happening.

Also, I did not know that, even though I'm in a bash kernel, indentation [of
"{QED_PROG}"] is somehow important. That's not at all expected, since spaces
aren't relevant in a bash script. But for some reason they're important in
this instance. Really, this all needs to be documented in some detail; it's
definitely non-obvious, unexpected behaviour.

I realise that octothorpes are significant in some languages, but at this
point we're inside a bash kernel (because of the "bash:" command), so I find
it unexpected that they aren't treated the way that a bash shell would treat them.

  Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by BoPeng** [comment] 2020-04-27 15:13
These features have been documented in detail https://vatlab.github.io/sos-docs/doc/user_guide/script_format.html 

SoS does not know `bash` or `sh` in particular. All it knows is that things under `sh:` is part of a script that is executed by the interpreter associated with `sh` (which in this case `sh`). 

So if you do

```
sh:
    line 1
    line 2

# my comment
```
SoS will take
```
    line 1
    line 2
```
as the script, and dedent it into 
```
line 1
line 2
```

Otherwise, it will take all lines after it before it reaches some SoS recognizable directives (such as another script). In you case, the comment 

```
line 1
line 2
# comment
```
is considered part of the shell script if you include the script without indentation

```
sh:
line 1
line 2
# comment
```
And everything is expanded.

If you really think these are confusing, you can write down the function call explicitly as

```
sh(f'''
line 1
line 2
''')
```

**Comment by BoPeng** [comment] 2020-04-27 16:50
The warning helps excluding comments from the shell script, but cannot stop the expansion of invalid expressions inside the script. #1364 explains the technique difficulties so I will close this ticket.

**Closed by BoPeng** 2020-04-27 16:50 UTC

**Comment by N7DR** [comment] 2020-04-27 21:52
Bo wrote on 4/27/20 9:13 AM:
> These features have been documented in detail https://vatlab.github.io/sos-docs/doc/user_guide/script_format.html 
> 

Well, perhaps if one already understands these details, that page makes sense.
I'm afraid that I can assure you that, for someone coming to all of this brand
new, even with nearly 50 years of background in practical programming, the
page just makes my eyes glaze over in un-comprehension. In fact, even now that
you've told me that the answer lies on that page somewhere, I can't see it,
unless somehow that's what the part entitled "Indented script format" is
trying to say.

I feel that, in order to assure you, I should say that the reason I'm still
here and trying to get a grip on this is because the basic idea of what the
sos workflow is trying to accomplish seems to be very powerful, and could be
great in helping to manage projects with large numbers of interdependent
pieces that are normally cobbled together manually (and with great fragility)
with bash/R/python scripts, makefiles and C++ executables. So I'm determined
to understand how to make it work, because in the end it seems like it will be
worthwhile. Learning something from scratch without a book, though, is *very*
difficult and horribly painful.

> SoS does not know `bash` or `sh` in particular. All it knows is that things under `sh:` is part of a script that is executed by the interpreter associated with `sh` (which in this case `sh`). 

OK, in that case, when it sees:
 sh:
     line 1
     line 2

 # my comment

you are telling me (aren't you?) that it invokes sh, which then starts to
execute what follows, which is:

     line 1
     line 2

 # my comment

so sh will perform the commands on line 1 and line 2, and then see a comment.
But that's not what's happening; it seems that there is some fundamental point
here that may be very obvious to you, but certainly isn't to me. Why soesn't
sh see the line
"# my comment"
and treat it as a comment.

You seem to be suggesting that sh doesn't even see that line for some reason.

> SoS will take
> ```
>     line 1
>     line 2
> ```
> as the script, and dedent it into 
> ```
> line 1
> line 2
> ```
> 

OK, but since it's all after sh has been invoked, why does the indentation matter?

I think that this is the crux of the confusion. It seems that somehow
indentation matters, even though this is bash, not python. But the
documentation you point to says "The indentation of scripts in the script
style is optional"... so that seems to say that indentation /doesn't/ matter
(although I'm not clear what "in the script style" means). So I'm getting
conflicting messages here, and don't understand at all this indentation issue
regarding the shell commands.

> Otherwise, it will take all lines after it before it reaches some SoS recognizable directives (such as another script). In you case, the comment 
> 
> ```
> line 1
> line 2
> # comment
> ```
> is considered part of the shell script if you include the script without indentation
> 
> ```
> sh:
> line 1
> line 2
> # comment
> ```
> And everything is expanded.
> 

At this point, I am totally lost.

You know, what seems to be missing is an up-front detailed explanation for
five-year-olds (I'm kidding about that bit) about the basic way in which sos
workflow parses cells in notebooks. I'm sure it's all very obvious to you, and
possiblycould be reverse-engineered from the examples and statements in the
documentation. It's as clear as mud to a newcomer with a different background,
though. We need our hands holding a bit until we understand how sos workflow
breaks down and interprets the input in the notebook cells.

> If you really think these are confusing, you can write down the function call explicitly as
> 
> ```
> sh(f'''
> line 1
> line 2
> ''')
> ```
> 

That's far worse; I'd never be able to follow any complex series of
dependencies written in that style.

  Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by BoPeng** [comment] 2020-04-27 22:04
>  it seems that there is some fundamental point here that may be very obvious to you, but certainly isn't to me. 

The point is that when you do

```
sh: expand=True
script
```
the entire "script" is expanded with variables interpolated before `sh` is called to execute the script.

If you have
```
sh:
script
```
then no interpolation will happen so `sh` will execute directly.

The problem here is that SoS interpolate the entire script before it sends the script to `sh`, but SoS does not understand what constitutes "comments" in shell. As I wrote in another ticket (#1364), if SoS were to handle "comments" correct, it has to understand the following:

```sh
# line is a comment
cat > file <<HERE
# line is not a comment and should be kept
HERE
```
and many other cases, which is simply not possible.

**Comment by BoPeng** [comment] 2020-04-27 22:08
Anyway, I actually share you pain in trying to understand how SoS works, as it took me a great deal of time on the documentation, yet it is difficult for myself to find the information I need. If you have some technical writing (reference manual, user guide etc) that you really like, please let us know and we will try to learn from them.

**Comment by N7DR** [comment] 2020-04-28 20:34
Bo wrote on 4/27/20 4:08 PM:
> Anyway, I actually share you pain in trying to understand how SoS works, as it took me a great deal of time on the documentation, yet it is difficult for myself to find the information I need. If you have some technical writing (reference manual, user guide etc) that you really like, please let us know and we will try to learn from them.
> 

Good technical writing is very rare: it's very difficult to do right. I spent
years writing international standards, and also wrote the standard text on
VoIP over cable systems, so I know how hard it is.

I think it's MUCH harder on the web. In a book you can start at the beginning,
assuming that the reader knows nothing, and logically build everything from
the ground up. On the web, when you document a feature, you have no idea at
all what the reader already knows, because the Web is essentially random
access. (Even if a book is also random access, via the index, the sequence
from start-of-the-book all the way through to end-of-the-book imposes a
recognised order. And in a book, one can take the time to describe things
properly, whereas on the web, you really can't make a topic longer than a
small number of screens.)

You can tell I'm a great fan of books. I can't think of a single technology
I've learned and ended up using over a long period where I didn't learn at
least the basic material from a book. Once having read a book, web-based
material can be very helpful to find the details of a problem one is trying to
solve; but without having read the book to start with, the web is very painful.

None of which provides the example(s) you asked for. But I really can't think
of any web-based documentation that is useful for learning a new technology.
Lots of it is useful for finding out how to solve a particular problem, but
not for the initial understanding of the technology (For example, I use
cppreference.com and cpluplus.com all the time even though I was on the C++
standards committee [long ago]; but I sure wouldn't want to learn C++ from any
web-based material).

  Doc

-- 
Web:  http://enginehousebooks.com/drevans
