### ISSUE TITLE
Shared functions between actions in different steps

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#816] opened 2017-09-27 23:57 UTC
Ideally I need something like this:

```
def foo():
   ...

[step_1]
python:
   foo()

[step_2]
python:
  foo()
```
Basically I have some utility functions used by many different steps in the same workflow. In this case it is difficult to maintain it if I copy it multiple times. It seems making it a utility function in a separate file is the only option, unless it is possible to propose something to address it? Note that this is not just Python functions. It should be utility functions for any other actions (eg R in particular)

**Comment by BoPeng** [comment] 2017-09-28 01:16
Do I miss anything? `foo` will be included to each step if it is defined in `[global]`.

**Comment by gaow** [comment] 2017-09-28 01:19
Not if it is part of an action:

```
[global]
def hi():
  print('hi')

[1]
python:
  hi()
```

```
Traceback (most recent call last):
  File "/tmp/tmphscvml7r.py", line 1, in <module>
    hi()
NameError: name 'hi' is not defined
ERROR: [default_1]: RuntimeError at line 299 of 

Failed to execute commmand python /tmp/.sos/default_1_0_71f9b512.py (ret=1, workdir=/tmp)
```

And certainly not for other actions such as R.

**Comment by BoPeng** [comment] 2017-09-28 01:22
I see what you mean. So you have to either

1. Use it outside of action

```
[1]
hi()
```

2. define it outside of sos
```
[1]
python:
   import hi from stuff
   hi()
```

3. Patch the script...
```
[global]
hi = '''def hi()'''

[1]
python(hi + '''
hi()
''')
```

The second method is the proper way to go.

**Comment by gaow** [comment] 2017-09-28 01:23
Yes I understand there are solutions to it. But you see it does generate fragments of scripts elsewhere. I'm wondering if there is an interest in formally addressing this.

**Comment by BoPeng** [comment] 2017-09-28 01:26
Then we have to do something like:

```
hi = '''
def hi():
    print('hi')
'''

[1]
python: prefix=hi
   hi()
```

**Comment by gaow** [comment] 2017-09-28 01:27
Exactly. Or something more formal than `'''` ...

**Comment by BoPeng** [comment] 2017-09-28 01:28
How formal? You mentioned that could be R functions etc so we cannot define them freely.

**Comment by gaow** [comment] 2017-09-28 01:32
Well I was actually only worried about the corner case where the function itself contains `'''`. eg.

```
hi = '''
def hi():
   print('''
this is SoS prefix for functions.
it is a cool feature
   ''')
'''
```

But I'm cool with it as long is the parser is robust enough to deal with it.

**Comment by BoPeng** [comment] 2017-09-28 01:34
SoS uses python syntax, you have to use `"""` and `'''` etc to make `hi` a proper string. I see this request as a way to patch a script while still using script format. The patch would be simple if you can figure out a good name for the parameter.

**Comment by gaow** [comment] 2017-09-28 01:38
I'm not sure if I get what you meant, but I was just hoping to have everything in one script, including the patch. eg

```
patch hi {
def hi():
  print()
}
```
I assume `{}` matching is not hard. But we are then introducing something very different from existing syntax ...

**Comment by BoPeng** [comment] 2017-09-28 01:44
I meant that you have to use

```
hi = """
def hi():
   print('''
this is SoS prefix for functions.
it is a cool feature
   ''')
"""
```

even

```
hi = '''
def hi():
   print(''' + "'''" + '''
this is SoS prefix for functions.
it is a cool feature
''' + "   ''') "
```
to define the string properly.

**Comment by BoPeng** [comment] 2017-09-28 01:46
Actually, there is an existing mechanism in sos, at least for report, something like

```
report: output='hi.py'
    def hi():
   print('''
this is SoS prefix for functions.
it is a cool feature
   ''')

[10]
python: input='hi.py'
   hi()
```

The `input` parameter is currently used by `Rmarkdown`, `report` although the content of the input files are appended to the script, not prepend to it.

Do you mind using files for this purpose?

**Comment by gaow** [comment] 2017-09-28 01:49
Yes sorry I get that part, but I was not sure about 

>  I see this request as a way to patch a script while still using script format. The patch would be simple if you can figure out a good name for the parameter.

which means I have to write a separate script for it. 

Then your latest post confirms that we do use files, but dynamically generated, as you've proposed. This option is good to me though it does look a bit hacky and one has to clean up that file afterwards. But I would certainly prefer that to the simple string definition with `'''`

**Comment by BoPeng** [comment] 2017-09-28 01:56
Insertion of files has its own advantages.. I mean, perhaps the file can be generated in another way, perhaps the file is designed to be permanent, and the parameter allows the inclusion of content from multiple files.

The problem is the order. In `RMarkdown`, the content of input files are appended to the specified script.

```
RMarkdown: input=['step1.md', 'step2.md']
  ## This is a summary report
```

I am not sure how to specify the order at which the files are inserted.

**Comment by BoPeng** [comment] 2017-09-28 01:59
Of course different actions can handle the same parameter in different way, so this is not a big problem, as long as there is no need to prepend a script and append another one.

**Comment by gaow** [comment] 2017-09-28 02:01
I see. All are great points! Im just trying to think if there is indeed a need to prepend / append / even in arbitary position. Not for now when `input` is used to feed in utility functions for those actions ... so maybe do what you proposed unless we can think of a valid case that suggests otherwise?

**Comment by gaow** [comment] 2017-09-28 13:45
It seems to be working for the MWE. 

```
report: output = '1.py'
def hi():
  print('hi')

[1]
python: input = '1.py'
  hi()

```

**Comment by BoPeng** [comment] 2017-09-28 14:58
Good, although the name `report` is a bit counter intuitive here. Also, text in `report` will be interpolated by action `report`, and text inserted by `input` will not be interpolated, leading to potential problems, so it is important to remember that texts in `input` are included verbatim.

![image](https://user-images.githubusercontent.com/9889312/30973629-351e70f8-a433-11e7-90f7-403dd449277c.png)

**Comment by BoPeng** [comment] 2017-09-28 15:05
And for Python, there are potential problems with indentation :-)

![image](https://user-images.githubusercontent.com/9889312/30974152-8b3dc8ca-a434-11e7-883d-45edf56429ef.png)

**Comment by gaow** [comment] 2017-09-28 15:23
Duly noted!

I think it is not a big deal, because the scope of variables is self-explanatory. And people should understand its behavior as utility functions. Even different editors can mess up indentations so Python users should be quite tolerable to that.

The bigger question is whether or not this is some good practice for reproducible research that we should advocate. I recall a few weeks ago we had some discussions RE use of utility functions. You convinced me that best practice is to keep everything in one SoS file. This feature is an important step towards that goal, though the interface it is implemented is a bit counter intuitive.

**Comment by BoPeng** [comment] 2017-09-28 16:12
If you include something that will change across projects, it is better to formalize it as Python module, R library etc and use proper import command. This feature is meant to help avoid writing the same functions repeatedly in embedded script, so the common part is supposed to be visible in the workflow as well.

**Closed** 2017-10-02 16:28 UTC
