### ISSUE TITLE
Failure to save results and signatures of completed subtasks when master tasks are killed

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1323] opened 2019-11-19 20:07 UTC
For my earlier submission of thousands of substeps (about 20K) as about 1K tasks each having 20 substeps, I got some failures. When I fix my code and resubmit, I see more submitted jobs than expected:

```
INFO: M20_8250b19e9a9b5435 submitted to midway2 with job id 63825899
INFO: M20_7c665000478155e5 submitted to midway2 with job id 63825901
INFO: M20_c2dbff87ce2436c9 submitted to midway2 with job id 63825904
INFO: Waiting for the completion of 50 tasks before submitting 1521 pending ones.
INFO: M20_366084e8befddcbb submitted to midway2 with job id 63825930
INFO: M20_2e099a81d3f2c361 submitted to midway2 with job id 63825932
INFO: M20_612b2a2a35f4d851 submitted to midway2 with job id 63825933
INFO: Waiting for the completion of 50 tasks before submitting 1518 pending ones.
INFO: M20_06aec99666ae8966 submitted to midway2 with job id 63825984
INFO: Waiting for the completion of 50 tasks before submitting 1517 pending ones.
INFO: M20_ee9a017c3c6a6af7 submitted to midway2 with job id 63826018
INFO: Waiting for the completion of 50 tasks before submitting 1516 pending ones.

INFO: Waiting for the completion of 50 tasks before submitting 1516 pending ones.
```

as you can see what happens is that the same failed task will still be resubmitted even though maybe 19/20 of them were successful they will only be skipped when the M20 task is executed. That means they claim the same resource and  stay in the queue. It thus takes lots of time to recover maybe only a handful of failed runs. What I have to do now is to remove all task from `~/.sos` and start with `-s build` in order to skip existing valid output. I think it would make sense to regroup substeps and  generate new tasks to avoid such overhead.

**Comment by gaow** [comment] 2019-11-19 22:10
Hmm actually I think for this case, for some reason the previously completed task were also submitted, because I see this in the `.err` file:

```
INFO: All 20 tasks in M20_2b4c01d441cc279f ignored or skipped
```

This means a job `M20_2b4c01d441cc279f` was submitted when all the sub-tasks have previously been completed. It went through the queue system as one of the 1.5K jobs, wait in the queue, got allocated resource but only to found that the 20 tasks have previously been completed. I wonder why it did not skip the outputs when they are there. But better yet I think we should regroup and submit only failed substeps -- I thought that's once the case at least? Because this is a pretty major issue that I should have noted before!

**Comment by BoPeng** [comment] 2019-11-22 19:25
The reason is that the signatures are kept in the master task file so sos has to re-execute the entire master task to decide which ones have been completed. Not sure how to fix this right now.

**Comment by gaow** [comment] 2019-11-22 19:30
Is it also behavior in the past? And what if we don't use `task` but just send workflow scripts to the cluster as proposed in #1321 ? Somehow I remember in the past there were some regroup behavior. My current "fix" is to remove `~/.sos` and `.sos` and use `-s build` to resubmit; otherwise it is impossible to  efficiently salvage a few failed substeps from thousands of substeps.

**Comment by BoPeng** [comment] 2019-11-22 19:33
The regroup behavior was caused by ignored substeps. When there is no `output`, we have to rely on task signature to ignore subtasks, and as I said subtask signatures are saved with master task.

**Comment by gaow** [comment] 2019-11-22 19:38
> When there is no output

What do you mean by this? For the `20 tasks in M20_2b4c01d441cc279f ignored or skipped` their output file do exist -- that is why I can use `-s build` to skip them. It is true that substeps can be ignored when they appear to run successfully, eg, when you rerun a successful workflow all of them will be ignored or skipped.

**Comment by BoPeng** [comment] 2019-11-22 19:52
I meant that when there is no `_output`, there is no substep signature so sos cannot ignore substeps before tasks are generated.

**Comment by gaow** [comment] 2019-11-22 19:58
Okay my point is that for my case there is `_output`. I edited my post above. Maybe it is a bug?

**Comment by BoPeng** [comment] 2019-11-22 19:59
Then there is a bug... In theory, sos should check substep signature, and no task will be generated if the substep is ignored, then the failed substeps (tasks) will be grouped.

**Comment by gaow** [comment] 2019-11-22 19:59
Okay let me put together a MWE to see if we can reproduce it.

**Comment by gaow** [comment] 2019-11-24 00:39
@BoPeng here is an MWE:

```
[1]
reps = [x+1 for x in range(10)]
input: for_each = 'reps'
output: f'{_reps}.rds'
task: trunk_workers = 1, queue = 'midway2_head', walltime = '1m', trunk_size = 10, mem = '2G', cores = 1, workdir = './'
R: expand = True
	Sys.sleep({'60' if _index > 3 else '120'})
	saveRDS({_reps}, {_output:r})
```

You see it has output defined. Also you see I asked for 1 minute per substep wall time but have some substeps run for 2 min so this script will fail due to time limit.

On UChicago cluster with [this template](https://github.com/vatlab/stress-test/blob/master/issue_6/issue_6.yml), I submit the job:

```
sos run issue_1232.sos -c issue_6.yml
```

output:

```
[MW] sos run issue_1232.sos -c susie_z.bm.yml 
INFO: Running 1: 
INFO: M10_bc4b359d3a4b95c0 submitted to midway2_head with job id 63959811
INFO: Waiting for the completion of 1 task.
INFO: Waiting for the completion of 1 task. 
...
WARNING: Task M10_bc4b359d3a4b95c0 inactive for more than 185 seconds, might have been killed.
ERROR: [1]: [1]: Failed to get results for tasks bc4b359d3a4b95c0, 34b5d4b0abc56bb7, 79ea373e8c17676a, f6c23ec102e8d38d, 6565b00aba5e4d30, 28a570891074db6e, 29d2ee265317e65c, f48e6e53e14dbe5e, 00ef86d02637fe76, 0d3ef962e492442f
```

as you can see it claims failure to get tasks for all 10 tasks. 

I submit it again by running exactly the same command above:

```
[MW] sos run issue_1232.sos -c issue_6.yml 
INFO: Running 1: 
INFO: M10_bc4b359d3a4b95c0 restart from status aborted
INFO: M10_bc4b359d3a4b95c0 submitted to midway2_head with job id 63960183

```

it reruns everything, even though in fact output `1.rds` to `6.rds` do exist. 

I expect here it will recognize that the first 6 substeps are successful and only work on the remaining 4 substeps.

**Comment by gaow** [comment] 2019-11-24 00:52
Also in both runs I get in the `err` file:

```
INFO: M10_bc4b359d3a4b95c0 started
slurmstepd-midway2-0018: error: *** JOB 63960183 ON midway2-0018 CANCELLED AT 2019-11-23T18:45:32 DUE TO TIME LIMIT ***
```

but with `sos status ... -v4` it says:

```
standard error:
================
Task M10_bc4b359d3a4b95c0 inactive for more than 151 seconds, might have been killed.
```

It would be nice to incorporate the PBS err into `sos status` -- I thought we have it but it was not recording the more useful information in this case?

**Comment by BoPeng** [comment] 2019-12-04 05:00
> It would be nice to incorporate the PBS err into sos status

`sos` updated, but your template has

```
      #SBATCH --output={job_name}.out
```
which creates `.out` file in working directory, but SoS only recognizes system `.out` file in `~/.sos/tasks`. After changing the lines to

```
      #SBATCH --output=~/.sos/tasks/{job_name}.out
```
sos should now be able to pick up the message, absorb into `.task` and display it.

**Comment by gaow** [comment] 2019-12-04 05:09
I see ... but the problem with `--output=~/.sos/tasks/{job_name}.out` is that it will leave numerous files under `~/.sos/tasks` folder that we might forget to delete. Also sometimes it is more straightforward to `cat *.out | grep ...` than to check each task using `sos status` so it makes sense to put `*.out` and `*.err` somewhere more obvious than `~/.sos/task`.

Is there a way that SoS still picks these files and absorb into `.task` regardless of where they are?

**Comment by BoPeng** [comment] 2019-12-04 05:18
`sos status` will absorb or remove these files so these files will not stay long in `~/.sos/tasks`... Currently SoS only checks `~/.sos/tasks` although this could be an option in the `hosts.yml` file, then I would avoid excessive options.

The task has been waiting for a while after being submitted. I will stop and leave it to you to confirm the updated behavior (showing cluster error message from command line and `sos status`).

**Comment by gaow** [comment] 2019-12-04 06:51
Nope still not showing in `sos status -v4`:

```
[MW] sos status M10_bc4b359d3a4b95c0 -v4
M10_bc4b359d3a4b95c0	submitted

Created 3 hr ago
Started 1 hr ago
Ran for 6 min
TASK:
=====
#1 of 10 subtasks:
R(fr"""Sys.sleep({'60' if _index > 3 else '120'})
saveRDS({_reps}, {_output:r})
""")

TAGS:
=====
1 1560d5f4ae420d13

ENVIRONMENT:
============
_depends              []
_index                0
_input                []
_output               [file_target('1.rds'), file_target('2.rds'), file_target('3.rds'), file_target('4.rds'), file_target('5.rds'), file_target('6.rds'), file_target('7.rds'), file_target('8.rds'), file_target('9.rds'), file_target('10.rds')]
_runtime              {'cores': 1,
 'mem': 2000000000,
 'num_workers': 1,
 'run_mode': 'run',
 'sig_mode': 'default',
 'verbosity': 2,
 'walltime': '00:10:00',
 'workdir': './'}
step_depends          Unspecified
step_input            Unspecified
step_name             '1'
step_output           Unspecified


M10_bc4b359d3a4b95c0.sh:
========================
#!/bin/bash
#SBATCH --time=00:10:00
#SBATCH --partition=broadwl
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=2G
#SBATCH --job-name=M10_bc4b359d3a4b95c0
#SBATCH --output=~/.sos/tasks/M10_bc4b359d3a4b95c0.out
#SBATCH --error=~/.sos/tasks/M10_bc4b359d3a4b95c0.err
cd ./
module load R/3.5.1
sos execute M10_bc4b359d3a4b95c0 -v 2 -s default

M10_bc4b359d3a4b95c0.job_id:
============================
job_id: 64129227
```

but under `~/tmp` folder,

```
[MW] cat M10_bc4b359d3a4b95c0.err
INFO: M10_bc4b359d3a4b95c0 started
WARNING: Task M10_bc4b359d3a4b95c0 aborted
/tmp/slurmd/job64129133/slurm_script: line 13: 42895 Killed                  sos execute M10_bc4b359d3a4b95c0 -v 2 -s default
```

this is transparent and nice. 

As I said, I would like to `cat *.err` and look at all potential issues. So if I have to choose, I'd rather have these files outside `~/.sos/task` and not absorbed by `.task` vs having them in   `~/.sos/task` and to be absorbed and removed. I'm using another ticket for the issue and have this ticket focus on discussing regroup task bug.

**Comment by BoPeng** [comment] 2019-12-04 20:43
Now, back to the root of this problem, when the task is killed, the task got no chance to save signatures of the completed subtasks. This is a hard problem to solve unless we save signatures of completed tasks to files, and got "picked up" when sos notices the tasks being killed. Even in this case, as I have said, the master tasks have to be re-executed before it could ignore completed subtasks.

**Comment by gaow** [comment] 2019-12-04 21:44
I see. So this is a rather particular "bug" when a task itself is killed (due to walltime in this case). But in ordinary cases if some substeps in a task fail (script return code != 0), then the next time SoS reruns it should be able to regroup and focus on the failed ones, right? That was the behavior in the past I hope it is not broken.

Now back to this problem: it seems then #1321 `-q none` mode can help because it will save file signatures as it completes rather than involving task signatures?

**Comment by BoPeng** [comment] 2019-12-04 22:36
`-q none` is different since the tasks are merged to substeps .... 

Yes, this is a particular case when running tasks are killed. If the tasks are allowed to complete, SoS will be able to get results from completed subtasks.

There are solutions, as always, but none will be trivial. Right now all information on subtasks are saved in memory and are written to task file when all subtasks are completed. What would be required are writing information to disk as soon as subtasks are done. One way is to change format to an incremental one, at least for master tasks. Another way is to cache subtasks results to separate files, and merge them to the master task either when everything is done, or when the task is killed but `sos status` is called to collect the residues.

**Comment by BoPeng** [comment] 2019-12-04 23:24
Just to prepare for the new file format,

1. When task files are retrieved, only `result` is of interest. https://github.com/vatlab/sos/blob/master/src/sos/hosts.py#L272

2. The results are combined from sub results at the end: https://github.com/vatlab/sos/blob/4289ed0a782cc21aeadd389265979b765319e972/src/sos/task_executor.py#L626, from a list of single results.

3. Result for individual task is collected here https://github.com/vatlab/sos/blob/4289ed0a782cc21aeadd389265979b765319e972/src/sos/task_executor.py#L712

So the least intrusive way would be removing the combine result part and leave it to when the results are needed.

**Comment by BoPeng** [comment] 2019-12-07 00:35
Seems to work now.

**Closed by BoPeng** 2019-12-07 00:35 UTC
Labels: bug, request, soon
