### ISSUE TITLE
Global `task` folder

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#752] opened 2017-08-06 05:37 UTC
Sorry for submitting many tickets but this one certainly is of low priority (tagged to `later`). The number of `task` files accumulated in `~/.sos` is a bit worrisome to me. I'm wondering how many files do people usually have there? I removed my `~/.sos/task` on Friday morning, and by this time I've got 61072 files in `~/.sos/task`. This is two days working on just one project. I understand the advantages to have global task but I'm worried there will eventually be too many files there. I'm thinking maybe we have to move it to local `.sos`, or an option for it at least; or some way to clean it up when there are too many of them ...

**Comment by BoPeng** [comment] 2017-08-06 05:39
`sos purge --age 2d` to remove all tasks older than 2 days?

**Comment by gaow** [comment] 2017-08-06 05:43
Sure, sorry I should have said to implement a way that "automatically" remove them when there are too may. Yes I'm aware of that option, and even if not, a `find` can always suffice. But my point is that a regular user does not even realize it can be a problem! Moving to local `.sos`, on the other hand, can really mess up people's Dropbox or git repos. My initial thought is to set a max number of files allowed (what would it be??) and remove from oldest tasks when there are too many files -- and at the same time generate a warning.

**Comment by BoPeng** [comment] 2017-08-06 05:48
We could use a database-like method to save all tasks into a large file but a daemon-like process would have to manage them on the remote host to accept tasks....

**Comment by gaow** [comment] 2017-08-06 14:08
It would help with many small files, but still does not help with the potentially many obsolete signatures. Is it true that conceptually for `/path/to/file.txt` there should be one task / signature only? This constraint is more fundamental in helping reduce the number of files stored.

**Comment by BoPeng** [comment] 2017-08-06 14:32
What does torque do about this? I remember that it only shows pending tasks but you can refer to completed ones with an ID

**Comment by gaow** [comment] 2017-08-06 14:43
I think torque might simply insert to and display result from some databases, but for our case do we have to compare with existing tasks whenever a new one is submitted? That's more complicated than torque and a database may have io problem when it is too large?

**Comment by BoPeng** [comment] 2017-08-16 16:20
One way to solve this problem is to let `sos status` automatically remove competed/failed tasks older than 1 month, or even 1 week if there are too many files. This will at least avoid infinite accumulation of task files.

**Comment by gaow** [comment] 2017-08-16 16:24
Yes this is good housekeeping. But does "removing completed tasks" indicate users will have to rerun old tasks from a week ago if they do revisit their project, without `-s build`?

**Comment by BoPeng** [comment] 2017-08-16 16:38
No. This only removes `task` and related `out`, `err`, `sh`files. The  signatures are still there, and the signatures are mostly local and could be cleaned with projects.

**Comment by gaow** [comment] 2017-08-16 16:42
I see. This is good idea. 

But this still does not fix the problem when for example users run and complete lots of simulations, then realize they need to make a tiny change in script, and rerun these simulations. Then old tasks are saved and never will be removed. I was intially suggesting moving to local task because suppose we have a project folder for an SoS script (like `vtools`), then we can implement some command to only keep the signatures currently involved in the script of interest. Of course there are big flaws in my proposal as is, but I think my point of worry is at least valid.

**Comment by BoPeng** [comment] 2017-08-16 17:01
Tasks are shared and do not have concept of a "source" project, especially when they are sent to remote host. This allows tasks to be monitors anywhere, not just from the machine from which the tasks are produced.

**Comment by BoPeng** [comment] 2017-08-16 17:08
I was  only partly correct because although tasks do not have "source", the project knows its tasks and `sos purge` by default removes all project related tasks. So in your case, you can run `sos purge` before submitting a new batch of tasks.

**Comment by gaow** [comment] 2017-08-16 22:02
I see, but

> the project knows its tasks and sos purge by default removes all project related tasks

and I want exactly the opposite, ie, only keep project related tasks signature and remove all obsolete signature from the same project, while leaving signatures of other projects, current or obsolete, intact. Is that possible via some `sos purge` options?

**Comment by BoPeng** [comment] 2017-08-16 23:24
`sos purge` purges all tasks related to workflows under the current directory, and leave tasks from other projects (outside of the current directory) intact. I think this is exactly what you need.

**Comment by gaow** [comment] 2017-08-17 01:03
I understand what it does. But I'm talking about removing "obsolete" signatures of a project. For example, the code for the project has been changed many times and generated a lot of signatures / task err/out files that will never ever be of any value. Then when a person finally is settled with the project, he can use someting like `sos purge --obsolete` to remove any signatures historically related to the project, but will not touch any of the most up-to-date signatures so that executing SoS again will not trigger reruns for the same project.

**Comment by BoPeng** [comment] 2017-08-17 01:11
But what is wrong with `sos purge` before the next run?

**Comment by BoPeng** [comment] 2017-08-17 13:53
I have a hard time imagining how this can be a serious problem with one project. I would prefer not to add any command/option until the extra signatures/task files become a real problem.

**Comment by gaow** [comment] 2017-10-30 03:55
The quota on the cluster system for `$HOME` directory is 30GB. I started to receive warnings recently RE quota limit exceeded. Turns out SoS was the culprit:

```
32G	./.sos
```
Pretty impressive considering I only have purged it all a couple of months ago!

**Comment by BoPeng** [comment] 2017-10-30 04:06
This is a bit hard to believe because these are all tiny files. Can you try to get a head count of different types of files and their sizes? Something like `du -ch .sos/tasks/*.tasks | grep total`.

**Comment by gaow** [comment] 2017-10-30 04:13
Ahh I already removed them all ... but I think I know what's going on -- as raised in #840 I do have generated some very large global data object that got pickled to disk for every task I run.

**Comment by gaow** [comment] 2017-10-30 04:19
Ok I have another computer that also has a lot in `.sos` that I was able to try what you suggested:

```
gaow@trico:~/.sos/tasks$ du -ch *.task | grep total
177M	total
gaow@trico:~/.sos/tasks$ du -ch *.def | grep total
35G	total
gaow@trico:~/.sos/tasks$ du -ch *.err | grep total
396M	total
gaow@trico:~/.sos/tasks$ du -ch *.out | grep total
7.3M	total
```

In any case, some automatic clean up would be helpful in the long run.

**Comment by BoPeng** [comment] 2017-10-30 05:05
Yes, it is clearly the size of your `.def` file. You can PM me one so that I can see what data is large.

**Comment by gaow** [comment] 2017-10-30 05:11
Here we go:

[M400_85afea1462030d119a1b198067b997b2.def.tar.xz.txt](https://github.com/vatlab/SoS/files/1426000/M400_85afea1462030d119a1b198067b997b2.def.tar.xz.txt)

I had to trick github to accept this attachment by adding `.txt` to the `tar.xz` extension. When you download and remove `.txt` you should see a `tar.xz` file of 112KB. Decompression this file gives you a `def` file of 52MB.

**Comment by gaow** [comment] 2017-10-30 13:35
Update: my script that submits 30K computations to remote cluster at `trunk_size = 300` (about 100 tasks submitted) has resulted in 5.9GB `def` files within a few hours.

**Comment by gaow** [comment] 2017-10-30 15:34
Right, and I think this info should be dropped for a `task` because most of those files are not relevant to an individual task. `_output` would be enough to keep. (same deal for `input` and long parameters etc). Is that right?

**Comment by BoPeng** [comment] 2017-10-30 15:34
The pickled output can be compressed quite a lot so it can be a good idea to compress it.

```
-rw-r--r--      1 bpeng1  MDANDERSON\Domain Users   1973771 Oct 30 10:28 output
-rw-r--r--      1 bpeng1  MDANDERSON\Domain Users    131672 Oct 30 10:32 output.gz
```

**Comment by BoPeng** [comment] 2017-10-30 15:35
The problem is that individual task could opt to use `input` or `output, say, in a single-file case.

**Comment by BoPeng** [comment] 2017-10-30 15:36
Or, we can scan `task` to check the sign of using complete `output`.

**Comment by BoPeng** [comment] 2017-10-30 15:38
We could also move `output` etc to the master task level if all subtasks have the same `output`.

**Comment by gaow** [comment] 2017-10-30 15:44
> We could also move output etc to the master task level if all subtasks have the same output.

This seems reasonable.

> The pickled output can be compressed quite a lot so it can be a good idea to compress it.

Yes ... particularly with `xz` we were able to reduce the size from 50MB to 100K! But `gz` is already good if we have to worry about performance.

**Comment by BoPeng** [comment] 2017-10-30 16:45
I have implemented both options, let me know how it works.

**Comment by BoPeng** [comment] 2017-10-30 18:50
Note that I used `zlib.compress` which is most convenient but not necessarily most efficient in terms of space and time. Since Python 3 now (supports xz compression](https://docs.python.org/3/library/lzma.html), you can play around it and replace the `zlib` compression with `xz` compression. The code should be easy to change with [compression](https://github.com/vatlab/SoS/blob/master/src/sos/sos_task.py#L68) and [decompression](https://github.com/vatlab/SoS/blob/master/src/sos/sos_task.py#L184) both as one liners.

**Comment by gaow** [comment] 2017-10-30 23:08
Great! Since my current run has completed (though left behind it large SoS `def` footprint) I'm going to have to work in exploring the results of computations ... I hope you do not mind I keep this ticket open (and assigned to me) so that I"ll remember to try it out in my next runs.

**Comment by BoPeng** [comment] 2017-10-30 23:10
You could start a few jobs and just check the size of def filed, or you can check it later if you are busy now.

**Comment by BoPeng** [comment] 2017-10-31 20:15
Let me know how the patch works for you so that I can make a next release. Thanks.

**Comment by gaow** [comment] 2017-10-31 20:54
Sure, i'll report this back by the end of today!

**Comment by gaow** [comment] 2017-10-31 23:19
I just submitted a new batch. The `def` file size looks interesting:

```
[MW] ll *.def
-rw-rw-r-- 1 gaow gaow 811K Oct 31 18:07 M400_b565bcda6c0047da4964359a1df260e0.def
-rw-rw-r-- 1 gaow gaow 1.6M Oct 31 18:07 M400_4de2b3868dc263d0687ed02962190a53.def
-rw-rw-r-- 1 gaow gaow 2.4M Oct 31 18:07 M400_3aa68b7371acdfa92848fa556a4d6a58.def
-rw-rw-r-- 1 gaow gaow 3.2M Oct 31 18:07 M400_97c34a1a06176f2dcf2d5f35a47bfdd4.def
-rw-rw-r-- 1 gaow gaow 4.0M Oct 31 18:08 M400_f877f045f6ec1989dc4c9bd7e303f9f5.def
-rw-rw-r-- 1 gaow gaow 4.8M Oct 31 18:08 M400_548679b625cc5958d053324b3c6af8f8.def
-rw-rw-r-- 1 gaow gaow 5.6M Oct 31 18:08 M400_3656b36d2f36bef84ee16b2dc12bffde.def
-rw-rw-r-- 1 gaow gaow 6.4M Oct 31 18:08 M400_0e84b9fee8409b4903aee4e45b16f35a.def
-rw-rw-r-- 1 gaow gaow 7.2M Oct 31 18:08 M400_a1f67b86a12705588a9e1f995d8da565.def
-rw-rw-r-- 1 gaow gaow 7.9M Oct 31 18:08 M400_3824d64dccc4b2bb54341d2fa7e0c820.def
-rw-rw-r-- 1 gaow gaow 8.7M Oct 31 18:08 M400_0416d0b9f70d52c4470f092796eac418.def
-rw-rw-r-- 1 gaow gaow 9.5M Oct 31 18:08 M400_c7937db80a6a939ad6459fbe9d103c6d.def
-rw-rw-r-- 1 gaow gaow  11M Oct 31 18:08 M400_50cb1ad01798c6c6c3ca02119e7af3a9.def
-rw-rw-r-- 1 gaow gaow  12M Oct 31 18:08 M400_67045974cc4d3ba98b61d46af234aeaf.def
-rw-rw-r-- 1 gaow gaow  12M Oct 31 18:08 M400_09014c2c7ba5d9aec433a927af22fc2d.def
-rw-rw-r-- 1 gaow gaow  13M Oct 31 18:08 M400_9388ca7358a85a16aa8999c155e379c4.def
-rw-rw-r-- 1 gaow gaow  14M Oct 31 18:08 M400_522b199c8d3a895d83d3d760e6866485.def
-rw-rw-r-- 1 gaow gaow  15M Oct 31 18:08 M400_5fc193bc7a03b3d8d04c6a5a5ae7f809.def
-rw-rw-r-- 1 gaow gaow  16M Oct 31 18:08 M400_8baf89cb7ffcb46e88eec2c6f5ddaf83.def
-rw-rw-r-- 1 gaow gaow  16M Oct 31 18:09 M400_ca62686448784c798d26caa0d2e47482.def
-rw-rw-r-- 1 gaow gaow  17M Oct 31 18:09 M400_e62139c20629c31f8e550f9a3b20be1a.def
-rw-rw-r-- 1 gaow gaow  18M Oct 31 18:09 M400_8c0f8e010fc0b9df0e67c0065c9525e2.def
-rw-rw-r-- 1 gaow gaow  19M Oct 31 18:09 M400_f2d56cdd16725dabdd10c078e92124a4.def
-rw-rw-r-- 1 gaow gaow  19M Oct 31 18:09 M400_5f28730aa4efb49740515a7fb4a14e67.def
-rw-rw-r-- 1 gaow gaow  20M Oct 31 18:09 M400_b9e31b422a18b1b194e544f3fb25c8aa.def
-rw-rw-r-- 1 gaow gaow  21M Oct 31 18:09 M400_214f527383e955d22df67b8fc108538a.def
-rw-rw-r-- 1 gaow gaow  22M Oct 31 18:09 M400_c090355f170a26ac10f4f3be3fd5ff34.def
-rw-rw-r-- 1 gaow gaow  23M Oct 31 18:09 M400_29827ded66eca836fdcfe5a9f447caa1.def
-rw-rw-r-- 1 gaow gaow  23M Oct 31 18:09 M400_fc2c59b3f7265b8e9b87f65d0a008f0f.def
-rw-rw-r-- 1 gaow gaow  24M Oct 31 18:09 M400_f63eab6e3b59619d574f14068361ec74.def
-rw-rw-r-- 1 gaow gaow  25M Oct 31 18:10 M400_0658847468afa44a181872a887242644.def
-rw-rw-r-- 1 gaow gaow  26M Oct 31 18:10 M400_6be2ffea6581fec607d5a4bb0d882651.def
-rw-rw-r-- 1 gaow gaow  27M Oct 31 18:10 M400_f4c79cb607d3a9e414fb2aa71c5cdd43.def
-rw-rw-r-- 1 gaow gaow  27M Oct 31 18:10 M400_fad8817a7bb960417866d8252d46b15f.def
-rw-rw-r-- 1 gaow gaow  28M Oct 31 18:10 M400_cc6dd956d8cfd37001dd06ca58ec7954.def
-rw-rw-r-- 1 gaow gaow  29M Oct 31 18:10 M400_16358fa7b4f12946c90bff0d2511140c.def
-rw-rw-r-- 1 gaow gaow  30M Oct 31 18:10 M400_18224aebf395bb7e567d1735d8b789b8.def
-rw-rw-r-- 1 gaow gaow  31M Oct 31 18:10 M400_5af02b6020df8bfbbe59e32242fa1425.def
-rw-rw-r-- 1 gaow gaow  31M Oct 31 18:11 M400_2ad0b6b9c906b44e8d59a310d1508a6c.def
-rw-rw-r-- 1 gaow gaow  32M Oct 31 18:11 M400_7ec269df53aebd792fdfab583169e496.def
-rw-rw-r-- 1 gaow gaow  33M Oct 31 18:11 M400_4f08c5a399958972d779dd80f558ff37.def
-rw-rw-r-- 1 gaow gaow  34M Oct 31 18:11 M400_6876b363ffc30b7a630e650d584d389d.def
-rw-rw-r-- 1 gaow gaow  34M Oct 31 18:11 M400_2f852adc905afacbcd8eb9b83d4a82f9.def
-rw-rw-r-- 1 gaow gaow  35M Oct 31 18:11 M400_823ec15f2cfb8b3188331dd013f59b83.def
-rw-rw-r-- 1 gaow gaow  36M Oct 31 18:11 M400_d0a8d98dd18e4569b4b387613a102704.def
-rw-rw-r-- 1 gaow gaow  37M Oct 31 18:12 M400_9c4e58316fd93aca14b0e80160fdb02a.def
-rw-rw-r-- 1 gaow gaow  38M Oct 31 18:12 M400_0c1059714256b9c959812fe8bb14f28a.def
-rw-rw-r-- 1 gaow gaow  38M Oct 31 18:12 M400_3c781d730a7d71ea54143cd54aae54f8.def
-rw-rw-r-- 1 gaow gaow  39M Oct 31 18:12 M400_33d14dbe356434b00a8cd2e6c23ccb25.def
-rw-rw-r-- 1 gaow gaow  40M Oct 31 18:12 M400_15244edd0ec5f9e9275fe53d1f412773.def
-rw-rw-r-- 1 gaow gaow  41M Oct 31 18:12 M400_b3a06e2cf24692495169ade2763379cb.def
-rw-rw-r-- 1 gaow gaow  42M Oct 31 18:13 M400_c19dcec06fd811cb1c40b915f6e95fcd.def
-rw-rw-r-- 1 gaow gaow  42M Oct 31 18:13 M400_feb7d0acec10abe94a45b8df1cce3ab7.def
-rw-rw-r-- 1 gaow gaow  43M Oct 31 18:13 M400_3a6f7d57e37904d364f66c50070bcc8a.def
-rw-rw-r-- 1 gaow gaow  44M Oct 31 18:13 M400_5cabc925c7c43150ff216cffba3bd90c.def
-rw-rw-r-- 1 gaow gaow  45M Oct 31 18:13 M400_56f48e5fa67ead0a38d2d43edfd5439b.def
-rw-rw-r-- 1 gaow gaow  46M Oct 31 18:14 M400_d67aeb99de9a3ab9a3a6d3a5bbf5ead2.def
-rw-rw-r-- 1 gaow gaow  46M Oct 31 18:14 M400_99241ea214382ea0eb98315712e11046.def
-rw-rw-r-- 1 gaow gaow  47M Oct 31 18:14 M400_987cd9422737e176d5dd85166afde3a8.def
-rw-rw-r-- 1 gaow gaow  48M Oct 31 18:14 M400_05ac579462409c2b7fc4f9e87967a069.def
```

It looks like information accumulate? I have >25K jobs. The relevant parameter setting for `task` is:

```
        trunk_size = 400, trunk_workers = 1
```

that's 25K/400 master jobs.

1. Information of all 25K jobs are still a bit redundant if they have to present in all master jobs.
2. As you can see the file size doesnt look right.

**Comment by BoPeng** [comment] 2017-10-31 23:23
But I need to verified this with one early and one later task files.

**Comment by gaow** [comment] 2017-10-31 23:51
Here, in `xz` format:

[defs.tar.xz.txt](https://github.com/vatlab/SoS/files/1432649/defs.tar.xz.txt)

Perhaps we should also consider `xz` format "default"? The compression rate is significantly better.

**Comment by gaow** [comment] 2017-11-01 00:04
BTW currently submitting 25K jobs results in `tasks` folder of size  2.5G

**Comment by BoPeng** [comment] 2017-11-01 00:49
You can replace `zlib` with `lzma` in `sos_task.py`, rerun your tests and check the size of the `def` files.

**Comment by BoPeng** [comment] 2017-11-01 01:02
You were not using the latest trunk because the first line of your task file has

```
SOSTASK1.1
```
whereas the latest one should be `1.2`.

The '1.2' version should have

```
[bpeng1@BCBMC02TX0SHHV2:~/Downloads]$ ls -l *.def
-rw-r--r--@ 1 bpeng1  895809667  52161681 Oct 31 18:48 M400_60dba1ac51f7314c0ce29ee8928a4b24.def
-rw-r--r--@ 1 bpeng1  895809667    829714 Oct 31 18:48 M400_b565bcda6c0047da4964359a1df260e0.def
-rw-r--r--  1 bpeng1  895809667  15429505 Oct 31 19:59 v1.2.def
```
although this is still larger than I expected.

**Comment by gaow** [comment] 2017-11-01 01:10
Oops right, I'm so sorry ... I did not update the SoS on the remote machine! Currently my queue on the cluster is full. This batch of jobs will not finish until tomorrow morning. I guess I can wait for your continued updates, then update my remote machine to rerun the jobs.

**Comment by BoPeng** [comment] 2017-11-01 01:20
Ok. The xz compr

**Comment by gaow** [comment] 2017-11-01 02:15
> Not sure what is going on but the xz compression works much better than zlib.

You mean fact that xz compresses 100 times better than zlib? It's surprising because no benchmark suggests that. But the concept of context-based compression sounds interesting:

https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Markov_chain_algorithm#Overview

I guess we should happily live with it if there is no performance issue. I'm going to submit a test job as soon as my current batch finishes tomorrow.

**Comment by BoPeng** [comment] 2017-11-01 02:26
OK, just replaced `zlib` with `lzma`. My explanation is that we have large trunks of repeated stuff (`output`). They are not identical as each task has one more element so `output` cannot be moved to master task level. `zlib` is local compression so it compress each `output` separately, whereas `lzma` might have done something more global and really compressed repeated `output`.

There is indeed some performance penalty, but the benefit clearly outweight the penalty:

```
-rw-r--r--@ 1 bpeng1  895809667  52161681 Oct 31 18:48 M400_60dba1ac51f7314c0ce29ee8928a4b24.def
-rw-r--r--  1 bpeng1  895809667    114230 Oct 31 21:24 lzma.def
```

**Comment by BoPeng** [comment] 2017-11-01 13:07
This is something more aggressive. Previously, automatic detection of signature vars are used to include variables that are used by tasks, and now they are used to exclude `input`, `output` etc if they are not used. The patch would exclude `output` from your task files, and substantially reduce their sizes, but it might break some code if the static step analyzer does not pick up `output` when it is actually used.

We will see how well this works.

**Comment by gaow** [comment] 2017-11-01 18:53
I just submitted the 2nd run. The previously 5.2GB task folder is now 3.9 MB, so I guess I have nothing to complain about! Will have  to see unwanted side effects with other jobs though because my current job batch is running happily.

**Comment by BoPeng** [comment] 2017-11-01 19:19
OK. Although there might still be problems with too many small files, I will close this ticket for now.

**Comment by gaow** [comment] 2018-06-11 19:49
Okay I'm reopening this ticket because of many complaints I receive from a colleague of mine who recently runs many quick & small `sos tasks` on the cluster. The symptom she reported is that SoS process simply hangs without any progress for 10min. I asked her to remove `~/.sos` and try again. It took > 5min to delete the folder, but it fixed the hang issue. Then I got the question such as why we do not automatically clean things up or why not using time-stamps ...

I think people are generally aware of existence of `.sos`, and because many are familiar with `.snakemake`, they know how removing `.sos` can help getting a fresh run. But not so much for `~/.sos` where our task signatures are stored. And it can be big (see discussions in other threads of this ticket). 

I'm wondering the following: 

1. Is there a way to automatically remove old signatures of the same step? I guess we need to define what it is meant by "the same step" -- I guess same parameter, input and output files, but not the actual code which people might edit a lot?

2. Sometimes there are temporary variables in global parameters and can be quite large. is there a way to skip keeping signatures for those? That is, something like `temp()` for variables?

**Comment by BoPeng** [comment] 2018-06-12 03:13
According to [this line of code](https://github.com/vatlab/SoS/blob/master/src/sos/tasks.py#L863) we remove tasks older than 30 days if it is not running. It certainly does not help for cases with "lots of small tasks in two days". 

The slowness caused not only by large number of small files, but also by the time to check the status, because sos needs to check time stamp even content of multiple files.. Let me see if I can cache results between status checks.

**Comment by gaow** [comment] 2018-06-12 03:41
Yes the 30 day clean up is useful to some degree. I was wondering about only keeping the "most recent successful version of script" but it seems perhaps difficult? 

It would be nice to try to optimize there and then I'll have to try lots of small tasks myself to verify how good it is. I guess the fact that it locates on a cluster file system makes the check even more time consuming.

**Comment by BoPeng** [comment] 2018-06-12 03:43
I am working on a patch that

1. check the status of a task, but also returns relevant files and their stamps.
2. Cache the results in a pickle file.
3. When we check the next time, if all relevant files are still available and have the same time stamp, return status directly.

In this way all failed and completed tasks would be cached ...

**Comment by BoPeng** [comment] 2018-06-12 04:37
Let me know how well this works.

**Comment by gaow** [comment] 2018-06-12 14:47
Great! I guess it will take some time to accumulate the task signatures before problems show up, but i'll certainly get there soon and see if there is still a concern. I'll leave the ticket open before I  get there.

**Comment by BoPeng** [comment] 2018-06-12 14:54
It took my new mac about 1 sec to get status of 10,000 tasks from cache, compared to about 8 seconds before. This is on a SSD drive with fast access to small files so I expect bigger improvement on servers and clusters.

**Closed** 2019-01-23 22:52 UTC
Labels: discussion, request
