### ISSUE TITLE
Inquiry: Converting SoS notebooks to a Jupyter Book?

### ISSUE THREAD

**Issue by mathieuboudreau** [vatlab/SoS#1204] opened 2019-02-01 14:07 UTC
Just reaching our if anyone in the community has tried this already, or if it would even be possible.

Jupyter Book: https://jupyter.org/jupyter-book/intro.html

I just tried it quickly, and it seems that the language for all the markdown cells are marked as "sos" (not Octave or MATLAB for my notebook), so the output html is just gibberish. Also, not sure how these cells could transfer data between them in different language for the "interact inline" mode.

Working Jupyter Book (python-only): https://brainhack101.github.io/introML-book/01/MAIN_tutorial_intro_to_nilearn.html
Repo: https://github.com/brainhack101/introML-book

My (very quick) attempt at a Jupyer Book using an SoS : https://mathieuboudreau.github.io/introML-book/01/MP2RAGE.html
Repo: https://github.com/mathieuboudreau/introML-book

**Comment by BoPeng** [comment] 2019-02-01 14:22
@gaow tried JupyterBook and found that it is a lot of work to convert our tutorials to JupyterBook (https://github.com/vatlab/sos-docs/issues/44). If you think the sos tags make it difficult for you to use JupyterBook, I think it is reasonable to add an option to our command

```
sos convert my.ipynb my_sos.ipynb
```
so that you can convert a SoS notebook to a non-SoS notebook. (Currently it converts a non-SoS notebook to SoS notebook).

I will work on that in a minute.

**Comment by BoPeng** [comment] 2019-02-01 15:23
https://github.com/vatlab/sos-notebook/commit/e247d333951ea07d267e86920e58a963ee02d15b

Check out the latest master, run

```
sos convert my.ipynb my_nonSoS.ipynb --kernel python3
```
Of course if you used multiple subkernels in the notebook, all of them will become `python3` cells ( a warning will be given), but this should be enough for the purpose of JupyterBook.

**Comment by BoPeng** [comment] 2019-02-01 15:32
Per `notebook` to `md`, sos already has the command

```
sos convert notebook.ipynb out.md
```
and it simply calls `jupyter nbconvert`. 

What is happening here is that `jupyter nbconvert` adds language info after code cell and output
```
```R
a=1
```
Since it does not know anything about the multi-kernel nature of SoS notebooks, it adds langauge `sos` to the output, resulting in

```
```sos
a=1
```
Converting a SoS notebook to a regular Jupyter notebook **will not help this** and we will have to do something to our `notebook -> md` converter...

**Comment by gaow** [comment] 2019-02-01 16:12
@BoPeng I put together a demo site applying your patch as discussed in this ticket. Here is the outcome:

https://gaow.github.io/jupyterbook-sos-demo

Notice I've disabled links to interactive notebooks (mybinder etc).

Everything is streamlined in [`release.sos`](https://github.com/gaow/jupyterbook-sos-demo/blob/master/release.sos). I implemented the kernel replacement but not the ipynb to MD conversion. You should be able to reproduce it quite easily without installing anything.

As you can see, converting the kernels only solves part of the problem. The SoS notebook magics are still messed up. And it is still a pain to read without syntax highlighting.

@mathieuboudreau maybe this workflow  [`release.sos`](https://github.com/gaow/jupyterbook-sos-demo/blob/master/release.sos) is useful to you. Notice that it is tailored to comply my structure of organizing files.

**Comment by BoPeng** [comment] 2019-02-01 16:17
The new markdown converter should add syntax highlighting to subkernel cells, right? I mean, before we dive into the final outcome, it should be helpful to check the intermediate `md` file and see what we are missing there.

**Comment by gaow** [comment] 2019-02-01 16:44
> The new markdown converter should add syntax highlighting to subkernel cells, right? 

Yes. But this will require modifying `jupyter-book` code to replace the nbconvert with `sos convert`. I can try that and see the outcome. i'll change it in my fork, 

https://github.com/gaow/jupyter-book

I can add you as collaborates to mess with it together :) But I'll do this first prelim implementation and report back here, to let you decide if we want to pursue it further.

**Comment by gaow** [comment] 2019-02-01 16:48
@BoPeng does `sos convert` accept "unknown" `nbconvert` arguments? these will be the lines I have to replace with `sos convert` in [this file](https://github.com/gaow/jupyter-book/blob/af62928cc7eba566fb7452341812da582d4eb33c/scripts/generate_book.py#L241): 

```
            # Run nbconvert moving it to the output folder
            # This is the output directory for `.md` files
            build_call = '--FilesWriter.build_directory={}'.format(path_new_folder)
            # Copy notebook output images to the build directory using the base folder name
            path_after_build_folder = path_new_folder.split(os.sep + BUILD_FOLDER_NAME + os.sep)[-1]
            nb_output_folder = op.join(PATH_IMAGES_FOLDER, path_after_build_folder)
            images_call = '--NbConvertApp.output_files_dir={}'.format(nb_output_folder)
            call = ['jupyter', 'nbconvert', '--log-level="CRITICAL"',
                    '--to', 'markdown', '--template', PATH_TEMPLATE,
                    images_call, build_call, tmp_notebook]
```

**Comment by BoPeng** [comment] 2019-02-01 17:11
Yes, but it will not use `sos-markdown` template if a template is specified (`--template`, `PATH_TEMPLATE`). So to use `sos-markdown`, you will have to derive your `PATH_TEMPLATE` from `sos-markdown`.

**Comment by gaow** [comment] 2019-02-01 17:14
Okay the default template is [this one](https://github.com/jupyter/jupyter-book/blob/master/scripts/templates/jekyllmd.tpl). i'll use the markdown template for now and see what it gives.

**Comment by BoPeng** [comment] 2019-02-01 17:19
That template also derives from `markdown.tpl` and it overrides ` {% block input %}` with extra

```
{% block input %}
{% if cell.source != '' %}
{:.input_area{% if 'hidecode' in cell.metadata.tags %} .hidecode{% endif %}}
```

and I extended in `sos-markdown`
```
{%- if 'magics_language' in cell.metadata  -%}
    {{ cell.metadata.magics_language}}
{%- elif 'name' in nb.metadata.get('language_info', {}) -%}
    {{ nb.metadata.language_info.name }}
{%- endif %}
```

with 

```
{%- if 'kernel' in cell.metadata -%}
    {{ cell.metadata.kernel.replace('SoS', 'Python3') }}
{%- elif 'magics_language' in cell.metadata  -%}
    {{ cell.metadata.magics_language}}
{%- elif 'name' in nb.metadata.get('language_info', {}) -%}
    {{ nb.metadata.language_info.name }}
```

So basically you will have to create a template that derives from `jekyllmd.tpl` and  incorporate the sos kernel stuff.

**Comment by gaow** [comment] 2019-02-01 17:35
Okay I came up with another version of `release.sos` that does not do the trick to convert kernels:

https://github.com/gaow/jupyterbook-sos-demo/blob/master/release_via_md.sos

It remains to hack the `juypterbook` source along the lines of what @BoPeng has suggested above; then worry about SoS notebook magics. As pointed out in https://github.com/vatlab/sos-docs/issues/44 without substantial CSS related work the current markdown format loses a lot information from SoS notebooks. I need to work on something else now but it would definitely be nice to make SoS notebooks work for jupyterbook. My money is still on that `jekyllmd.tpl` template. Perhaps that is the only thing we need to edit to make it work.

**Comment by BoPeng** [comment] 2019-02-03 02:33
@mathieuboudreau I will close this ticket because the SoS part is done (SoS Notebook to regular notebook and SoS to markdown) and the rest would involve customization on the JupyterBook side. However, I personally think going to the md route is not ideal because you will lose a lot of information. If you are looking for ways to construct a repository for all your notebooks, you might want to have a look at our user guide pages (https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html) where navigation buttons are used to move across notebooks without refreshing the entire page. The templates are [here](https://github.com/vatlab/sos-docs/tree/master/src/templates) if you want to customize them for your site.

**Comment by mathieuboudreau** [comment] 2019-02-03 17:09
Thanks for all your help @BoPeng and @gaow ! Sorry I was AWOL for a bit, I got a bit lost in the discussion here while it was going on, so while you were both working on this I tried some other stuff on my end, and found that by simply manually replacing the **\```sos** lines in the Jupyter Books markdown files by **\```python**, that the Thebelab interactive inline cells got activated. Doing that automatically would be indeed more of a Jupyter Book question, as their markdown files are generated with their `make book` commands. I don't know if this solution overlaps in any way with what you proposed above.

Here's a [live demo](https://mathieuboudreau.github.io/introML-book/01/mvp_sos.html) my own Jupyter Book running with SoS.

**Comment by mathieuboudreau** [comment] 2019-02-03 17:11
I'm also considering the style you showed in your example (sos_in_notebook.html), however the thing that Jupyter Books offers extra is the interactive inline cells provided by Thebelab. Yours look visually quite nice though.

**Comment by BoPeng** [comment] 2019-02-03 17:16
The latest version of the template would add ```Python3``` to the SoS cell (and `R` to `R` cell etc). This is done [here](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/sos-markdown.tpl#L8), you can change it to something else if `Python3` does not work.

The interactive feature is interesting but it requires a Jupyter server, right? Something worth investigation though.

**Comment by mathieuboudreau** [comment] 2019-02-03 17:31
Yeah, it uses Thebelab, which runs on a MyBinder server session

**Comment by BoPeng** [comment] 2019-03-02 14:09
FYI, we now have a JupyterHub configuration for SoS documentations, which allows users to run our tutorials on our live server, even create PRs to improve them. This would be usable for users with resources to host a public server.

**Closed** 2019-03-02 14:09 UTC

**Comment by sukhjitsehra** [comment] 2022-07-14 02:27
Hi @BoPeng ,

It is possible to convert .m octave files to jupyter notebooks via sos. 

Please suggest. Thanks

**Comment by BoPeng** [comment] 2022-07-14 15:34
What is the value of such a conversation? There is no computed code and "sections" in the `.m` file so the end result would be a notebook with a single cell containing all the `.m` code, which, if you really want to do it computationally, can be achieved by creating such a notebook by yourself and replacing the `src` element with the content of the `.m` file.

That said, sos provides a 'plugin' mechanism for you to write any converter so that you can implement `sos convert script.m script.ipynb`. I can provide more information if you are interested in taking that route.

**Comment by sukhjitsehra** [comment] 2022-07-19 16:00
Hi @BoPeng: Please share more information to create a plugin for converting octave scripts to notebooks. Thanks

**Comment by BoPeng** [comment] 2022-07-19 16:51
ok, basically `sos convert` looks for plugins in the format of python entrypoints

https://github.com/vatlab/sos/blob/40d0b6e1bd0006cf3e2b5e6bcb1a6dd74141f081/src/sos/__main__.py#L113

and you can see a bunch of converters registered here

https://github.com/vatlab/sos-notebook/blob/667486365d399147b451b2e8c44a3a2d14a4bc34/setup.py#L92-L99

and the converter should have a parser and a converter function

https://github.com/vatlab/sos-notebook/blob/667486365d399147b451b2e8c44a3a2d14a4bc34/src/sos_notebook/converter.py#L159

So essentially you can follow the example of sos_notebook to define such a function and expose to sos through an entrypoint.

Your converter will be very easy since it will only have one cell. All you need to do is to use the `new_notebook` function from `nbformat`

https://github.com/vatlab/sos-notebook/blob/667486365d399147b451b2e8c44a3a2d14a4bc34/src/sos_notebook/converter.py#L268

You could write a package by yourself, or submit a PR to https://github.com/vatlab/sos-matlab .
