### ISSUE TITLE
SoS memory usage for large workflows

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1213] opened 2019-02-16 05:14 UTC
When I submitted `sos` command to compute node to submit jobs, I was surprised at how much memory it uses. I asked for 16GB memory, but I get this : 

```
Job 57608706 exceeded memory limit (17451008 > 16384000)
```

I never realized it is such resource consuming.  @BoPeng Do you see this on your end? Should I try to create some large test jobs, or you've got some jobs you could use to test?

**Comment by BoPeng** [comment] 2019-02-16 05:21
What job are you running? sos usually takes a few MB of RAM. It could use a few hundreds if you have a complex workflow but should not be more than that.

**Comment by gaow** [comment] 2019-02-16 05:26
Oh okay looks like it should not happen. I'm looking into this. It's the workflow generated automatically with DSC -- will create a smaller example removing heavy computations but keeping the structure of the workflow, verify the memory usage on my own desktop (using [this script](https://github.com/gaow/misc/tree/master/monitor)) for you to reproduce.

**Comment by gaow** [comment] 2019-02-17 01:22
@BoPeng Attached is an example. I removed the core computations so there should not be any issues due to computations in each step. Here is what I found:

```
$ python monitor.py sos run main.sos
time elapsed: 5.55s
peak first occurred: 3.02s
peak last occurred: 4.03s
max vms_memory: 21.34GB
max rss_memory: 0.98GB
memory check interval: 1s
return code: 0
```

You see the actual memory usage is 0.98GB but allocated memory is very high. The example is bundled as attached:

[mem_test.tar.gz](https://github.com/vatlab/SoS/files/2872570/mem_test.tar.gz)

**Comment by BoPeng** [comment] 2019-02-17 19:02
Does not know how much virtual memory counts as I always check real memory `RSS`. Are you sure the job is killed due to virtual memory?

> `VIRT` stands for the virtual size of a process, which is the sum of memory it is actually using, memory it has mapped into itself (for instance the video card’s RAM for the X server), files on disk that have been mapped into it (most notably shared libraries), and memory shared with other processes. VIRT represents how much memory the program is able to access at the present moment.

**Comment by gaow** [comment] 2019-02-17 20:33
Perhaps that command above was overly minimal ... But for attached command even rss memory is 5.39GB. You can test the one below : 

[test.tar.gz](https://github.com/vatlab/SoS/files/2873392/test.tar.gz)

```
time elapsed: 58.87s
peak first occurred: 29.13s
peak last occurred: 29.13s
max vms_memory: 64.96GB
max rss_memory: 5.39GB
memory check interval: 1s
return code: 0
```

**Comment by BoPeng** [comment] 2019-02-18 03:56
```
(sos) [bpeng1@BCBMF5KWK0F8F69:~/Downloads]$ python monitor.py sos run main -v1 -s force
[###########################################################] 59 steps processed (1945 jobs completed)

time elapsed: 182.99s
peak first occurred: 75.03s
peak last occurred: 166.26s
max vms_memory: 148.45GB
max rss_memory: 1.67GB
memory check interval: 1s
return code: 0
```

```
(sos) [bpeng1@BCBMF5KWK0F8F69:~/Downloads]$ python monitor.py sos run main -v1
[###########################################################] 59 steps processed (30 jobs completed, 1915 jobs ignored)

time elapsed: 12.67s
peak first occurred: 6.08s
peak last occurred: 11.15s
max vms_memory: 144.72GB
max rss_memory: 1.36GB
memory check interval: 1s
return code: 0
```

I have huge vms memory and relatively smaller rss memory.

**Comment by gaow** [comment] 2019-02-18 04:00
Hmm this is interesting. It looks like it's a linux machine? Mine is Linux (Debian 9).

Currently the check interval is 1s. It can be modified via bash variable:

```
export MEM_CHECK_INTERVAL=0.1
```

In any  case, what do you think is happening? Also do you think 1.36GB is on the high end? My actual application is bigger than this.

**Comment by BoPeng** [comment] 2019-02-18 04:07
I do not know. In generally python is not good at memory management as large objects (nested dictionaries, large arrays) take a lot of RAM, and python's GC system means that peak memory usage is unpredictable and the peak can happen with both old (deleted but not released to system) and new variables. 

All these make it pretty difficult to check what is going on.

**Comment by BoPeng** [comment] 2019-02-18 04:37
On a Ubuntu VM,

```
$ python monitor.py sos run main.sos -v1
[###########################################################] 59 steps processed (1945 jobs completed)

time elapsed: 328.00s
peak first occurred: 224.06s
peak last occurred: 293.01s
max vms_memory: 10.19GB
max rss_memory: 1.17GB
memory check interval: 1s
return code: 0
```

**Comment by gaow** [comment] 2019-02-18 04:40
what if you set

```
export MEM_CHECK_INTERVAL=0.1
```

and run again? Actually I've tried two systems: on the cluster (Scientific Linux 7, which is essentially Redhat 7) it directly leads to disconnection to the cluster due to over the memory limit 2GB. On my desktop I was able to get that 5.39GB memory foot print

**Comment by BoPeng** [comment] 2019-02-18 04:42
```
(base) bpeng1@ubuntu:~/Downloads$ python monitor.py sos run main.sos -v1
[###########################################################] 59 steps processed (30 jobs completed, 1915 jobs ignored)

time elapsed: 16.80s
peak first occurred: 4.03s
peak last occurred: 16.63s
max vms_memory: 8.23GB
max rss_memory: 0.85GB
memory check interval: 0.1s
return code: 0

```

**Comment by BoPeng** [comment] 2019-02-18 04:46
Latest master and try again? Not sure if anything is related but I am using the master.

**Comment by gaow** [comment] 2019-02-18 04:49
Sure, this is what i got on the latest `master`:

```
time elapsed: 58.97s
peak first occurred: 32.33s
peak last occurred: 32.33s
max vms_memory: 62.61GB
max rss_memory: 4.78GB
memory check interval: 0.1s
return code: 0
```
...

**Comment by BoPeng** [comment] 2019-02-18 04:49
The second example from [this post](https://github.com/vatlab/SoS/issues/1213?_pjax=%23js-repo-pjax-container#issuecomment-464505349)?

**Comment by gaow** [comment] 2019-02-18 04:51
Yes that post has only one example right? The complete output is:

```
$ export MEM_CHECK_INTERVAL=0.1
$ python monitor.py sos run main.sos -v1 -s force
[###########################################################] 59 steps processed (1945 jobs completed)

time elapsed: 58.97s
peak first occurred: 32.33s
peak last occurred: 32.33s
max vms_memory: 62.61GB
max rss_memory: 4.78GB
memory check interval: 0.1s
return code: 0

```

My Python is:

````
$ python --version
Python 3.6.1 :: Continuum Analytics, Inc.
```

Maybe I should get Python 3.7???

**Comment by BoPeng** [comment] 2019-02-18 04:53
Cannot imagine such a huge difference, and the earlier report was on a Python 3.6.7 on mac.

**Comment by gaow** [comment] 2019-02-18 04:54
You are right Python 3.7.1 does not make it any better ...

**Comment by BoPeng** [comment] 2019-02-18 05:10
DAG of the workflow. Basically there are a large number of nested workflows...

![image](https://user-images.githubusercontent.com/9889312/52929226-24679080-3309-11e9-833f-61481fa8f172.png)

**Comment by gaow** [comment] 2019-02-18 05:19
It is both beautiful and ugly :P

**Comment by BoPeng** [comment] 2019-02-18 05:20
In theory nested workflows could grow out of the step that generates them, but that is too much work...

**Comment by gaow** [comment] 2019-02-18 05:27
Sorry I do not understand. Would you elaborate?

The nested workflow "design" was how I generated lots of benchmarks automatically via the DSC syntax. It is a stress test / challenge for SoS. But we are going to use this type of design a lot for benchmarking. Perhaps we can revisit this together later if we have more resource to do it; but any improvement at this point would be extremely helpful!

**Comment by BoPeng** [comment] 2019-02-18 05:29
I was just stating how the nested workflows are placed on the animation image. These subworkflows have their own DAG (in your case single step) but in theory they are generated by a step from the mother workflow so we could use some sort of dash line to connect the subworkflow from the steps on the master, but to do that I will have to merge graphs in the dot file which can be quite troubllesome.

**Comment by gaow** [comment] 2019-02-18 19:24
got a bigger job running and killed on a compute node with 32GB memory requested!


```exceeded memory limit (41185432 > 32768000), being killed```

**Comment by BoPeng** [comment] 2019-02-18 20:41
What is your `-j` setting? The waiting processes do use memory though.

**Comment by gaow** [comment] 2019-02-18 20:43
Good point -- I did not set `-j`. So the default is half the CPU threads available on that machine, which is 14 I believe ...

**Comment by BoPeng** [comment] 2019-02-18 21:08
Your monitor script could write a more detailed log file with command and usage so that we know if the memory is used for tasks (for which sos should have less overhead) or main step; is used evenly or for one of the processes.

**Comment by BoPeng** [comment] 2019-02-28 02:15
I assume this should also be resolved by #1218

**Comment by gaow** [comment] 2019-03-01 18:40
Sorry I have to reopen this one: for that `mnm.sos` workflow I'm still seeing this on the cluster:

```
time elapsed: 2339.69s
peak first occurred: 2039.70s
peak last occurred: 2039.70s
max vms_memory: 21.22GB
max rss_memory: 10.72GB
memory check interval: 1s
return code: 0
```

the `monitor.py` script is under `~/software` on the cluster, in case you'd like to see it for yourself. At this point everything else seems to be working perfectly and my overnight job last night was a straight success. I reran one step intentially just to verify the memory usage and this is what I got ...

**Comment by BoPeng** [comment] 2019-03-01 19:02
https://pypi.org/project/memory-profiler/

seems to be good tool to use.

**Comment by gaow** [comment] 2019-04-05 17:13
Reporting some updates here using the current SoS on [this dataset](https://github.com/vatlab/SoS/files/2873392/test.tar.gz).

```
[GW] export MEM_CHECK_INTERVAL=0.1
[GW] python monitor.py sos run main.sos -v1
[###########################################################       
time elapsed: 118.62s
peak first occurred: 95.17s
peak last occurred: 95.17s
max vms_memory: 7.01GB
max rss_memory: 0.67GB
memory check interval: 0.1s
return code: 0
``` 

The test script runs 3 minutes. The memory `vms` and `rss` now both seem less than when I posted [here](https://github.com/vatlab/SoS/issues/1213#issuecomment-464505349). Part of the reason is possibly better handling of large global variables? But still i bring this up because submitting the master job to a compute node and have SoS submit to cluster from there still fail. I've got to do it on the head node which fortunately has enough resource and does not kill my long running SoS process.

**Comment by BoPeng** [comment] 2019-04-05 18:03
Please send the configurations (PM if needed) and error message and let me see if I can reproduce with two VMs. I have been slow to finalize the remote features but I should be able to help if it is a bug.

**Comment by gaow** [comment] 2019-04-05 22:17
Thanks @BoPeng yes I've been trying to come up with submitted jobs to confirm and show but the cluster is so busy today that I'm still in queue since a few hours ago. What I would like to do is to ask for 4GB memory for `sos` process to submit jobs and see my example above crashes on it. 

But without submitting it, you can also reproduce the example above with the data I have. I think you've done that with earlier version of SoS [on VM here](https://github.com/vatlab/SoS/issues/1213#issuecomment-464581933) which has better memory footprint than on my computer. Still the VMS is large. I just want to confirm if this example will crash a cluster job where 4GB memory is requested. If so,  I think > 4GB overhead is already something worth attention .

**Comment by BoPeng** [comment] 2019-04-05 22:39
I still think `vms` does not mean anything. I have
```
time elapsed: 200.35s
peak first occurred: 84.78s
peak last occurred: 84.78s
max vms_memory: 78.92GB
max rss_memory: 0.95GB
memory check interval: 1s
return code: 0
```

**Comment by gaow** [comment] 2019-04-09 17:42
I wonder what the memory footprint looks like with `pypy`. 

I think I'll need to create a more complicated example for this. On my cluster, 

```
time elapsed: 395.07s
peak first occurred: 168.18s
peak last occurred: 168.18s
max vms_memory: 18.82GB
max rss_memory: 2.33GB
memory check interval: 0.1s
return code: 0
```

so the memory is 2.33GB. Since I requested 4GB memory it is clear that VMS memory is not relevant.

**Comment by gaow** [comment] 2019-04-09 17:43
I'm trying to make a minimal version of this:

```
$ cat slurm-5930*
Note that the current default version of R is 3.5.1.
slurmstepd-midway2-0301: error: Detected 1 oom-kill event(s) in step 59301778.batch cgroup.
Note that the current default version of R is 3.5.1.
slurmstepd-midway2-0046: error: Job 59306426 exceeded memory limit (54878040 > 49152000), being killed
slurmstepd-midway2-0046: error: Exceeded job memory limit
slurmstepd-midway2-0046: error: *** JOB 59306426 ON midway2-0046 CANCELLED AT 2019-04-07T21:25:32 ***
```

where 48GB memory on a machine to submit SoS jobs is not enough.

**Comment by BoPeng** [comment] 2019-04-09 17:49
pypy3 cannot complete the example you posted, or it was 10x slower so I could not see its completion.

For the slurm job, it is necessary to figure out memory usages of each processes, and this is why I recommended the memory profiler python module since it captures such information. If the problem was caused by two many R processes, you could try smaller `-j`.

It might be desired to add something like a `-M` option to limit the total number of processes, but it is not possible to implement because we  farm out external processes (e.g. `R`) and we cannot know in advance how much RAM, and it would be too late when we detect they are using too much RAM.

**Comment by gaow** [comment] 2019-04-09 17:54
> if the problem was caused by two many R processes, you could try smaller -j

What happens in practice is that these jobs are submitted to cluster. I think I should create a minimal working example with that and get back here. We can then profile with that non-trivial example.

> It might be desired to add something like a -M option to limit the total amount of RAM used

But if all jobs are remote tasks submitted to elsewhere you would not expect the submitter to use 54GB memory right?

**Comment by BoPeng** [comment] 2019-04-09 17:56
Are you saying that the remote job is a single task? In that case you should run the memory profiler on `sos execute task_id`.

**Comment by BoPeng** [comment] 2019-04-09 18:01
Also, if you set `max_mem='48G'` to your queue, the task will terminate itself when it uses more than 48G of RAM and terminate with an error message that could be seen from `sos status`.

**Comment by gaow** [comment] 2019-04-09 18:04
No the remote job itself is completely okay. What happens is the `sos main.sos` process that submits those jobs. Instead of running `sos` on my desktop or the login node I submit it to compute node where it submits the real remote jobs to other compute notes. And those jobs are fine. I'll try to make an example and get back.

**Comment by gaow** [comment] 2019-04-09 19:02
I confirm that reducing `-j` helps. Each thread uses about ~2GB memory in my case.

**Comment by BoPeng** [comment] 2019-04-09 19:06
So the job that fails has only SoS processes (no external tasks or jobs such as `R`)? This is indeed concerning although you should not need more than `-j4`  to submit tasks. The problem here is that the default `-j` can be quite large on a compute node with many cores (e.g. 48 cores will lead to `-j24`)

**Comment by BoPeng** [comment] 2019-04-09 19:09
> I confirm that reducing -j helps. Each thread uses about ~2GB memory in my case.

Does it make sense to set default to `max(cores/2, 8)`?

**Comment by gaow** [comment] 2019-04-09 19:29
> Does it make sense to set default to max(cores/2, 8)?

Good idea, we should do that ...

**Comment by gaow** [comment] 2019-04-09 20:53
> So the job that fails has only SoS processes (no external tasks or jobs such as R)? 

Yes

> This is indeed concerning although you should not need more than -j4 to submit tasks. 

Is this true no matter how many jobs we have? In other words there should not be a difference between `-j4` and `-j40` in this context?

**Comment by BoPeng** [comment] 2019-04-09 21:02
> Is this true no matter how many jobs we have? In other words there should not be a difference between -j4 and -j40 in this context?

Yes, there is only one instance of task engine (for each remote host) in the master process. So whereas tasks are prepared by each step worker, they are submitted only be the master process.

**Comment by gaow** [comment] 2019-04-10 00:04
I'll leave this ticket open to see if it works as expected. Because as we've observed in the past `-j` does not always control the number of processes well. That bug should have been fixed but it does not harm to stress test it.

**Comment by BoPeng** [comment] 2019-04-10 00:14
Sounds good. The number of processes is supposed to be `j+1` plus the number of non-terminal nested workflows, which is a feature we allow but strongly discourage.

**Comment by gaow** [comment] 2019-04-10 17:11
BTW can we make a release for this (so I'll ask other people to simply upgrade SoS not adding `-c 4`), if reasonable? Thanks!

**Comment by BoPeng** [comment] 2019-04-10 17:18
ok, only one real fix (#1246) but I  have just released 0.19.4 since all tests pass.

**Comment by BoPeng** [comment] 2019-04-10 17:21
hold on, my patch does not look right

```
default=min(max(os.cpu_count() // 2, 8), 1),
```

**Comment by BoPeng** [comment] 2019-04-10 17:22
It should be

```
default=min(max(os.cpu_count() // 2, 1), 8)
```

**Comment by BoPeng** [comment] 2019-04-10 17:26
Also, is `8` a reasonable default? Since sos itself takes 1 and 4 processes seems to be a reasonable number of "multi-processing" job, it looks to me that 

```
default=min(max(os.cpu_count() // 2, 1), 3)
```
can be a better "default" value.

**Comment by gaow** [comment] 2019-04-10 17:31
Well if most SoS users run pipelines as remote tasks then possibly this is a better default. But to run on a single desktop then I feel min(CPU/2, 8) is a good default, at least for a desktop workstation.

**Comment by gaow** [comment] 2019-04-10 17:32
and oops sorry indeed that earlier patch does not look right ...

**Comment by BoPeng** [comment] 2019-04-10 17:35
Fixed and made a new release.

**Comment by gaow** [comment] 2019-04-10 17:37
Great, thank you!

**Comment by gaow** [comment] 2019-04-10 22:08
Unfortunately, 4 threads did not help:

```
time elapsed: 698.82s
peak first occurred: 477.08s
peak last occurred: 477.08s
max vms_memory: 24.02GB
max rss_memory: 20.56GB
```

and I see the hanging behavior comes back. Using `ps` command I see `defunct` processes:

```
16829 pts/178  00:01:06 sos <defunct>
16977 pts/178  00:01:06 sos <defunct>
16979 pts/178  00:01:06 sos <defunct>
19202 pts/178  00:03:35 sos
49618 pts/178  00:02:19 sos
￼```

and after I `ctrl-C`, I get:

```
16829 ?        00:01:06 sos <defunct>
16977 ?        00:01:06 sos <defunct>
16979 ?        00:01:06 sos <defunct>
19202 ?        00:03:36 sos <defunct>
49618 ?        00:02:19 sos <defunct>
```

that is, everything is `defunct` now when `sos` should just quit. The only thing that looks correct is the number -- 5 processes is `-j4` + 1.

I'm trying to put together a minimal working example for this.

**Comment by BoPeng** [comment] 2019-04-10 22:14
Do you mean it worked locally but failed on a compute node with -j 4?

**Comment by gaow** [comment] 2019-04-10 22:24
This is what I'm trying to find out now. In principle `-j 4` should use the same amount of memory using task (remote) vs not task (local) runs? I never had memory issues whatsoever for local runs but I assume this is because the workflow is not large enough. I'm wrapping up something right now but should be able to provide MWE offline soon.

**Comment by gaow** [comment] 2019-04-11 00:47
Now I get:

```
[MW] ps -u gaow | grep sos
 5628 pts/46   00:03:16 sos
32614 pts/46   00:16:50 sos
34731 pts/46   00:04:37 sos
43916 pts/46   00:00:02 sos
51186 pts/46   00:03:16 sos <defunct>
51202 pts/46   00:03:17 sos <defunct>
```

When I kill it with `ctrl-c` this time all got killed. The memory usage is 18GB.

I did not finish all the run, but I think this is good enough a test? I've sent you the DM.

**Comment by BoPeng** [comment] 2019-04-11 13:21
For a real-world example, at some point I see a lot of messages like

```
2019-04-11 00:11:39,463 - DEBUG - WORKER 57007 - 15060.3Mb - SUBSTEP
REQUESTED: 4 workers (of which 0 is blocking), 14159 requested, 7509
processed
```

while the last number increases slowly, the "requested" number
increases rapidly. That means a large number of substeps are queued in
the controller waiting to be processed. The substep messages can be
large if it contains large variables.

A likely solution is for step workers to stop sending so many substeps all at once.

**Comment by gaow** [comment] 2019-04-11 13:26
> The substep messages can be
large if it contains large variables.

Each of them contains a copy of global variable, right?

**Comment by BoPeng** [comment] 2019-04-11 13:29
Yes. Unlike `concurrent=False` where all substeps are executed in the step worker and share the same global variables, concurrent substeps are sent to the master (then dispatch to substep workers) each with a copy of the global variables. So when the step worker sends tens of thousands of substeps all at once to the master, the master queues tens of thousands of global variables.

**Comment by BoPeng** [comment] 2019-04-11 13:48
Testing the following patch, basically the step worker will wait for substep results instead of sending new ones if there are 100 batches of substeps on the master side. `100` is arbitrary and needs to be adjusted because there could be more than 100 workers.

```diff
diff --git a/src/sos/step_executor.py b/src/sos/step_executor.py
index 3367cca..ab46647 100755
--- a/src/sos/step_executor.py
+++ b/src/sos/step_executor.py
@@ -684,8 +684,17 @@ class Base_Step_Executor:
     def process_returned_substep_result(self, till=None, wait=True):
         while True:
             if not wait:
-                if not self.result_pull_socket.poll(0):
-                    return
+                # 1213
+                cur_index = env.sos_dict['_index']
+                trunk_size = env.sos_dict['_runtime']['trunk_size'] if 'trunk_size' in env.sos_dict['_runtime'] and isinstance(env.sos_dict['_runtime']['trunk_size'], int) else 1
+                pending_trunks = (cur_index - self._completed_concurrent_substeps) // trunk_size
+                if pending_trunks < 100:
+                    # if there are more than 100 pending trunks (e.g. 1000 substeps if trunk_size is 10)
+                    # we wait indefinitely for the results
+                    if not self.result_pull_socket.poll(0):
+                        return
+                elif 'STEP' in env.config['SOS_DEBUG']:
+                    env.log_to_file('STEP', f'Waiting for more substeps to be completed before submitting new substeps (index={cur_index}, completed={self._completed_concurrent_substeps} pending_trunks={pending_trunks})')
             elif self._completed_concurrent_substeps == till:
                 return
             yield self.result_pull_socket
```

**Comment by BoPeng** [comment] 2019-04-11 14:14
A persistent queue on the master side sounds like a more robust solution

https://pypi.org/project/persist-queue/

Although we should use in memory queue with small applications.

**Comment by BoPeng** [comment] 2019-04-11 14:38
Just for reference, the following seems to be working

```
diff --git a/src/sos/workers.py b/src/sos/workers.py
index 52eaf10..eba85d3 100755
--- a/src/sos/workers.py
+++ b/src/sos/workers.py
@@ -5,9 +5,11 @@
 
 import multiprocessing as mp
 import os
+import pickle
 import signal
 import time
 from typing import Any, Dict, Optional
+from queuelib import FifoDiskQueue
 
 import zmq
 
@@ -318,7 +320,7 @@ class WorkerManager(object):
         self._worker_alive_time = time.time()
         self._last_pending_time = {}
 
-        self._substep_requests = []
+        self._substep_requests = FifoDiskQueue('testfilefile')
         self._step_requests = {}
 
         self._worker_backend_socket = backend_socket
@@ -341,7 +343,7 @@ class WorkerManager(object):
     def add_request(self, msg_type, msg):
         self._n_requested += 1
         if msg_type == 'substep':
-            self._substep_requests.insert(0, msg)
+            self._substep_requests.push(pickle.dumps(msg))
             self.report(f'Substep requested')
         else:
             port = msg['config']['sockets']['master_port']
@@ -414,9 +416,9 @@ class WorkerManager(object):
             self._worker_backend_socket.send_pyobj(None)
             self._num_workers -= 1
             self.report(f'Blocking worker {ports} killed')
-        elif self._substep_requests:
+        elif len(self._substep_requests) > 0:
             # port is not claimed, free to use for substep worker
-            msg = self._substep_requests.pop()
+            msg = pickle.loads(self._substep_requests.pop())
             self._worker_backend_socket.send_pyobj(msg)
             self._n_processed += 1
             self.report(f'Substep processed with {ports[0]}')
```
although it is a bad idea to use persistent queue all the time.

**Comment by gaow** [comment] 2019-04-11 14:41
So the idea is to use file-based not memory based queue? I think more fundamentally it might worth trying to reduce the size of the queue because 20GB on the disk is also a lot resource, not to mention the possible big I/O bottleneck.

**Comment by BoPeng** [comment] 2019-04-11 14:49
This is basically some work to confirm the source of the problem. It is hard to know the performance penalty for disk-based queue but after `-s build` through the workflow,

1. The on-disk queue is big

```
[MW] ls -lh ~/tmp/10-Apr-2019/testfilefile/q00000 
-rw-rw-r-- 1 gaow gaow 45G Apr 11 09:37 /home/gaow/tmp/10-Apr-2019/testfilefile/q00000
```
I did not check the source but I believe this simple implementation just store all processed and unprocessed messages on disk and use a pointer to bypass popped messages.

2. The maximum memory usage of the master process is 2.5G , in contrast to > 10G before.

I did not check the size of each substep but on-disk (or database) queue is unavoidable for large workflows. We just need to pick a solution with reasonable comprise between performance and memory/disk sizes.

**Comment by BoPeng** [comment] 2019-04-11 14:58
Note that I also had a patch that prevents step workers from submitting too many substeps to the master. Basically, the step worker knows how many substeps are being processed and can wait for results before submitting new ones. This can be a better approach but

1.  When `trunk_size` is involved, say, `trunk_size=1000`, we have to wait at least several "batches" because step worker processes return results in batch. We also need to avoid deadlock condition if the worker waits for part of a "batch" is not submitted.

2. In theory if there are many step workers, the master will still be swamped with substeps even if each step worker contributes, for example, 1000 substeps.

**Comment by BoPeng** [comment] 2019-04-11 18:34
Glad to realize that `trunk_size` does not matter so the problem is easy to fix. Just submitted a patch and make sure that there are at most 10 substeps waiting on the master side for each step worker. That means that will be at most 100 pending substeps for `-j10`, which is certainly tolerable and does not need to be persisted to disk.

Let me know if the patch works.

**Comment by gaow** [comment] 2019-04-11 19:02
Great, yes it works -- with `-j4` I now get 2.13GB RSS for what used to cost me >20G. Looks like we can close this issue, if I'm not being too optimistic!

**Closed** 2019-04-11 19:04 UTC
