### ISSUE TITLE
%from magic import class / function definitions from other sos scripts or SoS Notebooks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#778] opened 2017-08-20 00:16 UTC
SoS is a great book-keeping tool, but I still find myself relying on utility scripts for pure Python code (imported in SoS as `from .utils import ...`). Is it reasonable request to import from other SoS scripts functions and classes defined, as is? I can immediately see myself using a `utils.ipynb` to keep all my utility functions, nicely separated into sections, subsection, etc, documented with markdown cells here and there, tested with scratch pad and %preview, rendered to nice HTML for review, and above all be able to load to all other SoS scripts and notebooks. Currently we have 

```
%from utils include some_step
```

and hopefully we can also have 

```
%from utils import some_functions, some_classes
```

**Comment by BoPeng** [comment] 2017-08-20 01:35
The technical problem here is that SoS is not fully compatible with Python so the usually `import` mechanism would not work, so we have to physically include the code and interpret it.

**Comment by gaow** [comment] 2017-08-20 03:03
I see. So this makes it difficult to use and share utility functions -- unless they are written in `*.py` file which is outside the SoS scripting environment. Are there some workaround to streamline this better?

**Comment by gaow** [comment] 2017-08-20 03:25
There is a mechanism to import Python modules from notebooks:

http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Importing%20Notebooks.html

Looks straightforward, and we can make SoS register this hook by default so that in sos environment the regular `import` for Python will import from notebooks. This will make life a lot easier. At least I do not have to leave SoS notebooks for my scripting / book-keeping. Of course users  have to be responsible for whether or not  what they import make sense.

**Comment by BoPeng** [comment] 2017-08-20 03:34
The problem is that sos notebook is much more complex than python notebook, which contains pure python code and markdown. If we are to mimic the example, we have to skip non-sos cells, and for sos cells we have to skip magics, and how about header, directive etc? So in the end you might want to only import cells in `Python3` language?

**Comment by gaow** [comment] 2017-08-20 03:35
> So in the end you might want to only import cells in Python3 language?

Indeed. And I think that link I sent already does it.

**Comment by BoPeng** [comment] 2017-08-20 03:40
The link you sent execute all code cells... but if you are to use Python3 cell, why not just use Python3 notebook and this mechanism? As far as I can see, functions defined in the Python3 cells in that SoS notebook cannot be transferred to SoS kernel...

**Comment by gaow** [comment] 2017-08-20 03:50
> The link you sent execute all code cells.

It does not matter because I'll have to ensure that notebook only contain `def` and `class`. The pages says: "Since IPython cells can have extended syntax, the IPython transform is applied to turn each of these cells into their pure-Python counterparts before executing them. " it will skip magics including those from `sos`

> but if you are to use Python3 cell, why not just use Python3 notebook and this mechanism?

You mean for the utility notebook? Yes sure, I can create a pure Python 3 notebook to use this mechanism. But for my main notebook I do not want to use Python 3 notebook. I basically want to source Python functions to my SoS notebook from another notebook (if Python 3 notebook is easier I can stick to Python 3 notebook for utilities).

> As far as I can see, functions defined in the Python3 cells in that SoS notebook cannot be transferred to SoS kernel...

I do not understand this, because if SoS can source from a regular Python script, then with this mechanism it should be able to source from another (Python 3) notebook, if we simply add to SoS by default all the codes this wiki page suggests?

**Comment by BoPeng** [comment] 2017-08-20 04:00
For the third point, I meant that the sos cells in the notebook with the python3 functions cannot make use of functions defined in Python3 cells, so you might as well separate the python3 functions to python3 notebooks.

**Comment by gaow** [comment] 2017-08-20 04:05
> For the third point, I meant that the sos cells in the notebook with the python3 functions cannot make use of functions defined in Python3 cells, so you might as well separate the python3 functions to python3 notebooks.

Yes that's understood! Hopefully you see my proposed user case is simply trying to conveniently load Python 3 modules from carefully written notebooks (that only has definitions not executions). Whether that notebook be a pure Python 3 notebook or an SoS notebook (in which case we have to find a way to only load from Python 3 cells) really does not matter here. Conceptually I agree load from a Python 3 notebook is even clearer -- and users will understand all we do is a wrapper to that wiki page method.

**Comment by BoPeng** [comment] 2017-08-20 04:12
But then you might as well define them in `.py` files that can be imported without any trick, which could be unavailable, for example, when the task is executed remotely.

I understand your use cases but including external sources is against the design idea to have everything explicitly defined in a sos file. It also makes things really complicated, when, for example, sending a script/workflow or task to be executed remotely. I myself would stick to the idea of defining utility functions at the end of the file with a separate `[global]` section. If something really need to be reused, defining them as proper Python modules makes more sense to me.

**Comment by gaow** [comment] 2017-08-20 13:40
What works for me now is to implement a python script that extract from Jupyter notebook the function / class definitions. So I now keep a notebook of Utils at the end of which I have this cell:

![screenshot from 2017-08-20 08-33-51](https://user-images.githubusercontent.com/917985/29495343-21a7eece-8583-11e7-9b00-dbf8979201b8.png)

But this is the result of my way of project organization. I'm sure it is not the best way, but seems a reasonable compromise?

**Comment by BoPeng** [comment] 2017-08-20 13:54
Not sure what this `extract_function.py` does but it is trivial (and could be useful) to implement converters such as `.pynb -> .py` and `.pynb->.R`. Basically we just grab `python2/3`/`R` cells and export them. 
 We could also export content of `Python` and `R` actions. Converters are static so it is not possible to expand string interpolation but at least users could get something to started, and if the exported scripts could be executable if the cells do not use string interpolation.

**Comment by gaow** [comment] 2017-08-20 13:59
Here is what `extract_function.py` does: it only extracts the `def` and `class` from a notebook to write some "modules".
 
```python
import argparse, re
'''
Usage: python extract_function.py --from A.py --to B.py C.py
'''
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--from", dest = "source")
    parser.add_argument("--to", nargs = '+')
    args = parser.parse_args()
    output = []
    harvest = False
    for line in open(args.source).readlines():
        if line.strip().startswith('#'):
            continue
        if line.startswith('import') or line.startswith('from'):
            output.append(line)
        if line.startswith('def') or line.startswith('class'):
            harvest = True
            output.append(line)
            continue
        if harvest:
            if line.lstrip() != line:
                output.append(line)
            else:
                output.append('\n')
                harvest = False
    for item in args.to:
        with open(item, 'w') as f:
            f.write(''.join(output))
```

It's silly code that I put together quickly to get something work. Grabbing code cells and output may lead to problems here because I'd only want to export as modules. I guess this is the only difference from your suggestion.

**Closed** 2017-10-30 15:11 UTC
Labels: wontfix
