### ISSUE TITLE
Use md5sum for large input parameters / variables

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1008] opened 2018-08-08 00:14 UTC
For parameters, with or without `parameter:` statement, we currently save them as is. But suppose I have this setup: 

```
[global]
x_mat = simulated_large_matrix()
```

and `x_mat` will be passed through every step of the workflow. As a result signature for each step can be large. For example I've got 4759 task files in `~/.sos/tasks`. The total size is 258M. This is just a result of about 9 hours of computation. I think we should worry about task file size and use md5sum for large input variables.

**Comment by BoPeng** [comment] 2018-08-08 16:30
As I have said, output variables are required so have to be saved. Input context variables are now saved with only their signatures. Hopefully the problem could be resolved with the new method to save compressed signature to sqlite database.

**Closed by BoPeng** 2018-08-08 16:30 UTC

**Comment by gaow** [comment] 2018-08-10 14:46
> As I have said, output variables are required so have to be saved. Input context variables are now saved with only their signatures.

Sorry I just want to clarify this: input context variable means parameters, and variables in `global` section? What does output variables mean -- only those `shared` with other steps?

**Comment by BoPeng** [comment] 2018-08-10 14:56
These are all context variables (e.g. result of an assignment etc). Whereas all input variables need to checked (currently using md5), most output variables are not shared and actually do not need to be tracked. The problem is that we process `shared` after steps are executed so there is currently difficult to selectively save output variables in signatures.

I suppose feature request can be submitted to remove unused output variables from signatures to improve efficiency.
