### ISSUE TITLE
`-s build` does not construct signatures for auxiliary steps

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#743] opened 2017-08-02 02:50 UTC
For my MWE (same MWE from another issue):

```
num = 5
n = [x for x in range(num)]
parameter: file_set1 = ["1_{}.out".format(x) for x in range(num)]
parameter: file_set2 = ["2_{}.out".format(x) for x in range(num)]

[init1]
parameter: input_files = list
parameter: output_files = list
input: for_each = ['n']
output: output_files, group_by =  1
task:
run:
 echo ${_n} > ${_output}
print('init1')

[init2]
parameter: input_files = list
parameter: output_files = list
input: dynamic(input_files), group_by = 1
output: output_files, group_by =  1
task:
run:
 echo ${_input} > ${_output}
print('init2')

[run_A]
output: file_set1
sos_run('init1', input_files = [], output_files = file_set1)

[run_B: provides = file_set2]
depends: sos_step("run_A")
output: file_set2
sos_run('init2', input_files = file_set1, output_files = file_set2)

[1]
depends: file_set2
```

If I run it once, then temporarily move my `~/.sos` and `.sos` to elsewhere, and run it again with `-s build`, then supposedly I should get signatures re-generated. This is not the case. And consequently after running with `-s build` I run again without  `-s`, then everything gets re-executed. I do not recall seeing this before so I suspect it is `Make` style specific?

**Comment by BoPeng** [comment] 2017-08-02 03:21
Yes, I think the reason is that sos looks for existing files and stops there when the files exist. It does not care and does not build signature for the files.

**Comment by gaow** [comment] 2017-08-02 15:40
Sorry I just want to confirm -- this is indeed a bug, right? Your `Yes` in the thread above is related to my `Make style specifc` comment?

**Comment by BoPeng** [comment] 2017-08-02 15:43
Yes, this is make-style specific and I am not quite sure what would be the correct behavior. I will think about it.

**Comment by BoPeng** [comment] 2017-10-23 21:04
I think this is a `WONTFIX`. By design the makefile style will only execute a step when the outcome does not exist, so if you have all the output, re-running the workflow will ignore these steps, even in `build` sig-mode.

**Closed by BoPeng** 2017-10-23 21:04 UTC
Labels: bug, wontfix
