### ISSUE TITLE
Database lock err message in `~/.sos/task`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1012] opened 2018-08-09 19:41 UTC
It did not seem to have impacted my jobs, but I found some `err` files in my `~/.sos/task` folder:

```
[MW] ls tasks/*.err
tasks/0248bc81f1f4e2a1.err  tasks/82d279401ffea297.err
tasks/12d23b96dc3ebee4.err  tasks/90a217ea8812fe2b.err
tasks/3ff6a4dcb24ae859.err  tasks/a0cb245c8ec456de.err
tasks/4d33042c851752be.err  tasks/bf8241e985b859d9.err
tasks/667e2e9b7896b46d.err  tasks/db0d470cd00a4d77.err
[MW] cat tasks/*.err
2018-08-08 18:18:44,089: DEBUG: 0248bc81f1f4e2a1 ``started``
2018-08-09 12:52:52,761: DEBUG: 12d23b96dc3ebee4 ``started``
2018-08-09 12:53:17,724: DEBUG: 12d23b96dc3ebee4 ``completed``
2018-08-09 12:54:09,953: ERROR: database is locked
2018-08-09 12:52:20,733: DEBUG: 3ff6a4dcb24ae859 ``started``
2018-08-09 12:52:49,520: DEBUG: 3ff6a4dcb24ae859 ``completed``
2018-08-09 12:53:50,113: ERROR: database is locked
```

But all my jobs were successfully completed. I'm not sure how to reproduce the behavior. Maybe there are some fixes based on first principles; then I can just keep monitoring all my future runs to see if it persists?

**Comment by BoPeng** [comment] 2018-08-09 19:44
These files are supposed to be removed after job completion. Let us monitor under what condition they are left.

**Comment by gaow** [comment] 2018-08-09 19:49
> Let us monitor under what condition they are left.

Okay that'd be a secondary issue, right? The biggest problem is perhaps the locked database thus failure to save signatures?

**Comment by BoPeng** [comment] 2018-08-09 20:08
I tested the lock mechanism with 10 processing writing continuous to it and it passed. How many concurrent jobs do you have? Do they have a large number of files? I suspect that locking under NFS is much slower, or even worse sqlite does not lock under NFS.

**Comment by gaow** [comment] 2018-08-09 20:26
> How many concurrent jobs do you have? 

For my morning run I have 700 concurrent jobs, each job has one input and one output file. But I set my `max_tasks` parameter to 60. Either way, there is certainly more than 10 processes. 

I should add that I only see 8 instances of bad locks under `~/.sos/task`:

```
[MW] cat *.err | grep lock | wc -l
8
```

still as you said many more `err` files were perhaps removed anyways so there might be more than 8.

**Comment by BoPeng** [comment] 2018-08-09 20:57
Here is the script I used to test signatures. Please run it with options like

```
$ python test.py --dir ~/sos/sos -j 5
It took 5 processes  2.9 seconds (21.7 per 10000 files) to process 1353 files under 242 directories
```
to see if you can reproduce deadlocks.

```
from sos.targets import file_target, path
import argparse
import multiprocessing
import time
import os
import glob

def write_signature(root, dirs, files):
    #print(f'processing {len(files)} under {root}')
    for file in files:
        file_target(os.path.join(root, file)).write_sig()
    return len(files)


def testWriteSignature(dir, njobs):
    sig_file = os.path.join(os.path.expanduser('~'), '.sos', 'target_signatures.db')
    if os.path.isfile(sig_file):
        os.remove(sig_file)

    pool = multiprocessing.Pool(njobs)
    res = pool.starmap_async(
            write_signature, os.walk(dir))
    return res.get()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dir', help='directory to generate signature')
    parser.add_argument('-j', '--jobs', type=int, help='number of processes')
    args = parser.parse_args()

    st = time.time()
    res = testWriteSignature(args.dir, args.jobs)
    print(f'It took {args.jobs} processes {time.time() - st : .1f} seconds ({(time.time() - st)*10000/sum(res):.1f} per 10000 files) to process {sum(res)} files under {len(res)} directories')



```

**Comment by gaow** [comment] 2018-08-09 22:03
Im trying to run the test on my cluster NFS. It seems there is no explicit sqlite lock / release used?

**Comment by BoPeng** [comment] 2018-08-09 22:05
sqlite supports multi-processing and has its own read/write lock. I have set the lock delay to 20s so a process would wait 20s before it sends out a database lock message.

I am still checking.

**Comment by BoPeng** [comment] 2018-08-09 22:12
Script updated to validate signature to check if all signatures are saved.

**Comment by BoPeng** [comment] 2018-08-09 22:16
On SSD
```
$  python test.py --dir . -j 20
It took 20 processes  2.0 seconds (14.9 per 10000 files) to process 1354 files under 242 directories
It took 20 processes  0.2 seconds (1.4 per 10000 files) to process 1354 files under 242 directories
$  python test.py --dir . -j 1
It took 1 processes  2.0 seconds (14.4 per 10000 files) to process 1354 files under 242 directories
It took 1 processes  0.2 seconds (1.6 per 10000 files) to process 1354 files under 242 directories
```
On NSF:
```
$ python test.py --dir . -j 20
It took 20 processes  39.2 seconds (95.3 per 10000 files) to process 4109 files under 320 directories
It took 20 processes  3.0 seconds (7.2 per 10000 files) to process 4109 files under 320 directories
$ python test.py --dir . -j 1
It took 1 processes  40.7 seconds (99.1 per 10000 files) to process 4109 files under 320 directories
It took 1 processes  2.6 seconds (6.4 per 10000 files) to process 4109 files under 320 directories
```
and I do not see any database locked issue.

**Comment by gaow** [comment] 2018-08-09 23:09
Neither do I on NSF:

```
$ python test.py --dir ~/GIT/mvarbvs/dsc/susie_comparison -j 30

It took 30 processes  1861.1 seconds (184.6 per 10000 files) to process 100803 files under 13 directories
```

let me rerun the updated version.

**Comment by gaow** [comment] 2018-08-10 01:35
Still flawless. If there is a lock error it should show on the terminal right? what do you suggest we should do -- is there a way to prevent this from first principles? An ad hoc approach, as I can remember in vtools load genotypes for association, was that we try 5 times before in fact throw an error message ... not sure something similar can be applied here for every write operation.

**Comment by BoPeng** [comment] 2018-08-10 02:16
The `timeout` parameter of sqlite3 already has internal repeat. We can increase time out from 20 to 60 under the assumption that the lock will be released eventually.

Also I tend to think we should reduce this to a warning, since the worst that can happen is that the signature is not written so the step would be rerun if we rerun the workflow, but in reality most workflow will not be rerun, right?

**Comment by BoPeng** [comment] 2018-08-10 02:35
I will make a new release for the fix of `sos purge`.

**Comment by gaow** [comment] 2018-08-11 21:31
I'm still getting the error even after 60s wait. Under the directory where I save my task err messages:

```
[MW] cat *.err | grep locked | wc -l
21628
```
There are quite a few.

**Comment by BoPeng** [comment] 2018-08-11 23:03
What is the entire line? I am wondering what database is causing the problem.

**Comment by BoPeng** [comment] 2018-08-11 23:06
You can then share with me the database and I will see the size of records.

**Comment by gaow** [comment] 2018-08-11 23:15
Oops just deleted that current project due to a hang error ... I'm still trying to figure out the cause of the hang (a bit to messy to report anything now). Let me report on that in a new ticket later. 

> What is the entire line? I am wondering what database is causing the problem.

I deleted the earlier project but here I salvage one from an earlier project: 

```
WARNING: Failed to save signature for target lm_less/liter_data_53_summarize_ld_1_lm_less_3.pkl: database is locked
```

Nothing special about this. But I do notice those error messages were written at about the same time point.

**Comment by BoPeng** [comment] 2018-08-12 01:46
Ok. In the new branch I have consolidated most target signatures to step signatures so there is less traffic. Unfortunately the ranch is not quite ready. The commit before the latest one actually passed all tests so you could try it.

**Comment by gaow** [comment] 2018-08-12 14:16
Update: I now see these 2 types of messages:


```
INFO: fit_susie (index=1498) is ignored due to saved signature
```

which checks signature, and 

```
INFO: M2_e3829455156a4702 already completed
```

tells me some tasks are completed thus not submitted. The latter is interesting because I was able to find the expected output from these tasks but their signature were not saved. But the task status now captures this and prevented re-execution?

**Comment by gaow** [comment] 2018-08-14 00:15
Okay I'm running some local jobs on a very slow desktop hard drive on my desktop. The desktop is at the same time running some I/O intensive jobs (I can feel the slowness in system due to the I/O operations!). Then I get with SoS:

```
WARNING: Failed to write workflow signature of type input_file and id 7dd7343c0a8ed7f0: database is locked
WARNING: Failed to write workflow signature of type input_file and id f9ad1ebd06d1ce8b: database is locked
WARNING: Failed to write workflow signature of type dependent_file and id 7dd7343c0a8ed7f0: database is locked
WARNING: Failed to write workflow signature of type dependent_file and id f9ad1ebd06d1ce8b: database is locked
WARNING: Failed to write workflow signature of type dependent_file and id 7dd7343c0a8ed7f0: database is locked
WARNING: Failed to write workflow signature of type dependent_file and id f9ad1ebd06d1ce8b: database is locked
WARNING: Failed to write workflow signature of type output_file and id 7dd7343c0a8ed7f0: database is locked
WARNING: Releasing an non-existent or released lock for 7dd7343c0a8ed7f0.
WARNING: Failed to write workflow signature of type output_file and id f9ad1ebd06d1ce8b: database is locked
WARNING: Releasing an non-existent or released lock for f9ad1ebd06d1ce8b.
WARNING: Releasing an non-existent or released lock for 09f2004c82e3c18f.

```

Here is the database from my `.sos` folder: 

[sos_db.tar.gz](https://github.com/vatlab/SoS/files/2285091/sos_db.tar.gz)

Hope it helps!

**Comment by BoPeng** [comment] 2018-08-14 00:42
We can use a file-based lock to explicitly lock the database files so that only one process can write to it. Or we can send all information to the master process and let it write to the database. The former is trivial but can make database writing a lot slower, the former is more complex and error prone...

**Comment by BoPeng** [comment] 2018-08-15 00:56
With the patch the database entry should have been significantly reduced. Please let me know if you continue to observe database lock problem.

**Comment by gaow** [comment] 2018-08-15 13:09
I think the issue is still that there always will be a problem if we rely on "default" behavior of sqlite. I've got a 3 year old disk on my desktop which is becoming very slow recently. For example I run an enrichment analysis application which has lots of sqlite read / write unrelated to SoS but it drags the disk extremely slowly. Then at the same time I run a separate very light load SoS with dozens of output files though. Then this SoS process will have database lock problem, apparently due to the very slow disk I/O.

That said, I'll continue to observe if behavior for non-stress case has improved.

**Comment by BoPeng** [comment] 2018-08-15 13:35
There are two main databases now, the step signature database and the workflow logging database. The problem you have observed were from the (almost) write-only (if no report is generated) workflow database. Because it is write-only, there is no need for immediate commit because one process does not need to know what another process has hidden (uncommitted).

So the problem with workflow logging can be addressed in a number of ways. One is for each worker to write to its own database and do a merge from the master when sos exits. The other is holding the write to disk till workers exit. There is a high chance of collision at this time because workers exit about the same time, but since there are just a few writes, we can process-lock the database for this.

The step signature database is more complex. I want to say there is no need for a worker to read a signature that is written by another worker because for any given step, we either read a signature from a previous run, or write a new signature. Unfortunately, in a complex scenario we cannot rule out the case that a worker executes a step (in a nested workflow) and write a signature, and the other worker needs to execute the same workflow (with a different parameter) and need to check signature. Therefore step signatures need to be written to databases immediately, thus more chances of database lock.

**Comment by gaow** [comment] 2018-08-15 13:42
Thanks for the explanations. It sounds like the step signature is more likely the culprit and unfortunately has no easy alternatives. But you said:

> The problem you have observed were from the (almost) write-only (if no report is generated) workflow database. 

you can tell this from my error report and databases attached, right? I wonder why a seemingly easier operation (than step signature database) is in fact more error prone? How do I know if I get step signature database lock instead: the error prompt will be different?

**Comment by BoPeng** [comment] 2018-08-15 13:57
Yes. The warning messages will be different. But with my patch that reduced number of transactions from thousands (one transaction per file) to tens (one transaction per step), the database lock should happen at a much lower rate, and I tend to think we should test the current version more before jumping on a fix.

**Comment by BoPeng** [comment] 2018-08-31 00:09
I can finally reproduce the database locked issue on a samba mount:

```
 WARNING: Failed to write workflow signature of type tracked_files and id 9faf6f683016e63d: database is locked
TRACE: Write signature 9faf6f683016e63d
WARNING: Failed to write workflow signature of type tracked_files and id 155f8ce26ffe1e13: database is locked
TRACE: Write signature 155f8ce26ffe1e13
```

I will repeat my workflow and find a way to address the lock issue.

**Comment by BoPeng** [comment] 2019-02-28 02:20
Please re-open if the problem still exists.

**Closed by BoPeng** 2019-02-28 02:20 UTC
